### ISSUE TITLE
Forêt ouverte: table émergente pas possible de rouvrir 

### ISSUE THREAD

**Issue by victoriaDIF2023** [infra-geo-ouverte/igo2#1002]
1.	La petite fenêtre émergente se ferme par fois et ce n’est pas possible de la rouvrir. (voir vidéo)

https://github.com/infra-geo-ouverte/igo2/assets/143826751/73076a2b-0fcd-4b73-9064-c508cafcf452

**Comment by pelord** [comment]
Le bouton permet d'aggrandir la fenetre pour echanger entre la petite taille et la grande taille.

Pour ouvrir le panneau (toast), il s'agit de cliquer sur le bandeau vert....

**Comment by victoriaDIF2023** [comment]
ok, parfait je comprends, mais je pense que c'est pas intuitif. Merci

**Comment by pelord** [comment]
Je vais probablement enlever le bouton 
![image](https://github.com/infra-geo-ouverte/igo2/assets/7397743/c2cbed8e-e6c5-41b7-a484-2ce4aff3afe7)

lorsque le toaster est fermé

![image](https://github.com/infra-geo-ouverte/igo2/assets/7397743/24cac8db-eebe-498c-a82c-3de42d49f9d6)

**Comment by pelord** [comment]
Car le bouton permet de changer le statut de la fenetre lorsqu'elle est ouverte.. entre petit et grand format

**Comment by pelord** [comment]
![2023-09-01_15-42-41](https://github.com/infra-geo-ouverte/igo2/assets/7397743/06d688cf-edbd-48f2-841c-9299c58c3db8)

**Comment by victoriaDIF2023** [comment]
c'est parfait on va avoir la flèche seulement lorsqu'elle est fonctionnelle

**Comment by pelord** [comment]
Sera corrigé dans la prochaine version (v16.0.0 +)
https://github.com/infra-geo-ouverte/igo2/commit/bcc3f49e1bb3e82627efc0a84d2f96e05261a8bc
