### ISSUE TITLE
iCherche - Simplifier le menu de configuration

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2#1011]
Contexte:
Selon plusieurs de nos clients, le menu de configuration de iCherche "Écart Maximale" est trop compliqué pour l'utilisateur moyen et n'est pas vraiment utilisé.

Objectif
Ajouter un paramètre de configuration qui permettrait d'afficher ou non le menu écart maximale. Conserver les paramètres par défaut actuel.

Objectif Secondaire:
Analyser le comportement du nombre de résultat. Est-ce vraiment utilisé, est-ce que le "Voir plus de résultat" avec la pagination de l'API de iCherche est suffisante?

**Comment by alecarn** [comment]
C'est une configuration au niveau de iCherche `showAdvancedSettings` qui est par défaut a true et qui peut être configurer dans le `config.json` ou l'`environnement.ts`
![image](https://github.com/infra-geo-ouverte/igo2/assets/133774929/9dc21c77-809e-4d3c-a5a2-5627d03009f3)

Cela permet d'afficher ou non les paramètres avancés, pour l'instant seulement l'Écart Maximale
![image](https://github.com/infra-geo-ouverte/igo2/assets/133774929/36fada25-f519-4498-88b3-9950479f7f55)

**Comment by LAMM26** [comment]
ok dans 16.0.0-rc.3
