### ISSUE TITLE
Typography adjustment

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2#1024]
Report all typography adjustment

1. Table header is now 16px and was 14px, the Material default is also 14px. The table header use the `subtitle-2` config

**Comment by alecarn** [comment]
The new base value for Material:
![image](https://github.com/infra-geo-ouverte/igo2/assets/133774929/f22d44de-9925-4b12-af93-122b8163ef07)

The default IGO2-LIB:
![image](https://github.com/infra-geo-ouverte/igo2/assets/133774929/6e52144a-f0f5-42d8-975e-2c5049542500)

**Comment by MSPKarengeo** [comment]
When I start the visit in the home window, I see the font size too large for the size of the frame. 

<img width="325" alt="image" src="https://github.com/infra-geo-ouverte/igo2/assets/90481471/1b95f3af-a065-4c8c-9269-9ee80de1733c">
