### ISSUE TITLE
On ne peut plus agrandir les getinfos

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#1061]
La grandeur du getinfo ne change pas lorsqu'on clique sur les flèches pour agrandir:

![image](https://github.com/infra-geo-ouverte/igo2/assets/56965082/6409730b-e2b9-43a8-ac30-92ff4eeff282)

**Comment by aziz-access** [comment]
@coulo3 la description n'est pas clair.
Besoin plus d'info screenshot de l'app, erreur dans la console de dev, vidéo...

**Comment by aziz-access** [comment]
pour tester ce bug il faut définir le queryFormat de la couche a iframe: 
```
{
 ...,
  "sourceOptions": {
  ...,
  "queryFormat": "htmlgml2",
   "queryHtmlTarget": "iframe",
  } 
}
```
