### ISSUE TITLE
Exportation couche dessin sur Forêt ouverte appareil mobile

### ISSUE THREAD

**Issue by victoriaDIF2023** [infra-geo-ouverte/igo2#1081]
Lors de l'exportation de la couche dessin sur appareil mobil le résultat est un fichier texte et si on essaye de le réimporter un message d'erreur s'affiche
[Drawings.geojson.txt](https://github.com/infra-geo-ouverte/igo2/files/13281435/Drawings.geojson.txt)
![Screenshot_20231107_081844_Chrome](https://github.com/infra-geo-ouverte/igo2/assets/143826751/87bebf68-4ce7-4f11-ac8c-d04a2e8a02be)
![2023-11-07_08-26-22](https://github.com/infra-geo-ouverte/igo2/assets/143826751/5211a748-b116-4aaa-bd5a-96186f14e72b)

**Comment by alecarn** [comment]
Fonctionnel, testé avec la preprod sur Android
