### ISSUE TITLE
Problème barre de défilement des outils à gauche

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#1083]
En étant dans Ma carte, je ne peux plus défiler les outils à gauche. en cliquant sur la flèche descendante, c'est l'outil Partager qui ouvre au lieu de défiler les autres outils. 

![image](https://github.com/infra-geo-ouverte/igo2/assets/56965082/c668aef7-903a-43b6-9744-ad810a1029ca)

Bizarrement le bogue est reproduisible seulement sur un écran d'ordinateur portable. Si  on essaie via l'émulation ou la redimensionnement c'est le scrollbar qui s'affiche.

Pour reproduire:
1- Ouvrir IGO2 sur un ordinateur portable
2- Ouvrir le menu et cliquer sur un item.
3- Une flèche dans le bas devrait s'afficher

**Comment by alecarn** [comment]
Conforme en preprod
