### ISSUE TITLE
problème d'affichage de l'unité de mesure sur mobile

### ISSUE THREAD

**Issue by aziz-access** [infra-geo-ouverte/igo2#1084]
Problème d'affichage de l'unité de mesure dans l'outil de dessin en mode mobile.
Problème d'affichage de l'unité de mesure dans l'outil Filtre spatial en mode mobile.
Problème d'affichage de l'unité de mesure dans l'outil Mesurer en mode mobile.

![image](https://github.com/infra-geo-ouverte/igo2/assets/119948730/536091d9-4a8b-48e5-9c7a-6a442cc03e0c)

**Comment by alecarn** [comment]
Conforme en preprod
