### ISSUE TITLE
L'impression haute résolution n'est pas fonctionnelle sur certains appareils mobiles

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2#1085]
L'impression haute résolution (300 PPP) est non fonctionnelle sur certains appareils mobiles. Sur de vieux appareils l'app gel tandis que sur iOS la carte imprimée est blanche.

Pour l'instant nous avons désactivé la sélection de cette résolution pour tous les appareils. 

Objectif:
1- Réintégrer la haute résolution pour les ordinateurs et Anrdoid
2- Investiguer la raison pour laquelle ça ne fonctionne pas sur iOS et si résolu, réintégrer la haute résolution pour tous les appareils
3- Investiguer pourquoi pour certain appareils moins puissant l'application gel.

**Comment by aziz-access** [comment]
La principale raison du problème de l'impression en haute résolution sur mobile est la limite de mémoire et le timeout.

**Comment by alecarn** [comment]
Conforme en preprod
