### ISSUE TITLE
support couche WMS / layer / getcapabilities

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#114]
Support dans la config du JSON : couches WMS par le URL+layer ou le getcapabilities ("protocole": WMS, protocol:getcapabilities, title, scalemin, scalemax, wms_dataurl_href, wms_dataurl_format, active, visible, opacity).

**Comment by matrottier** [comment]
exemple : 
```json
{
      "name" : "Découpage administratif",
      "type" : "wms",
      "source":{
        "url" : "http://geoegl.msp.gouv.qc.ca/cgi-wms/bdtq.fcgi/",
        "params" : {"LAYERS": "admin",
                    "VERSION": "1.1.1"}
      }
    }
```

pour le paramètre "source" : http://openlayers.org/en/latest/apidoc/olx.source.html (voir olx.source.ImageWMSOptions)

**Comment by matrottier** [comment]
active, visible, opacity ne sont pas dans le getCapabilities ...
c'est dans notre getlegend custom ?

**Comment by gignacnic** [comment]
http://openlayers.org/en/latest/apidoc/ol.source.html#.WMSServerType
 
ol.source.WMSServerType{string}

    Available server types: 'carmentaserver', 'geoserver', 'mapserver', 'qgis'. These are servers that have vendor parameters beyond the WMS specification that OpenLayers can make use of.
