### ISSUE TITLE
Param dans URL : pour déclencher une recherche de localisaton/couche et affichage de couche

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#117]
Pouvoir passer en paramètre dans l'URL, une recherche de localisation ou l'affichage d'une couche.
Exemple : http://geoegl.msp.gouv.qc.ca/gouvouvert/?recherche=adresse&texte=1735%20bourgogne,%20chambly ou https://camptocamp.github.io/ngeo/master/examples/contribs/gmf/apps/mobile/index.html/theme/OSM?lang=fr&tree_groups=OSM%20functions%20mixed%2CLayers%2CGroup%2COSM%20functions%2CExternal&tree_enable_osm_scale=true&tree_group_layers_Layers=cinema%2Cpolice%2Cpost_office%2Centertainment%2Csustenance%2Chospitals&tree_group_layers_Group&tree_group_layers_OSM%20functions=osm_scale&tree_group_layers_External=ch.swisstopo.geologie-geotechnik-gk500-lithologie_hauptgruppen&baselayer_ref=map

**Comment by mbarbeau** [comment]
Ajouter dans la librairie: https://github.com/infra-geo-ouverte/igo2-lib/pull/60

Voici les options disponibles:
context=nomContexte
center=-73.5,-46.8 (lon, lat)
projection=EPSG:4326
zoom=5

**Comment by gignacnic** [comment]
J'imagine que tu as ajoutés aussi l'option: 
layer=wms_layer_name ?
