### ISSUE TITLE
Plus bel favicon...

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#127]
Faire un favicon standard (64x64 ?) basé sur : igouverte.org dans la bonne résolution pour le raccourci de téléphone. Exemple : http://www.favicon-generator.org/download/2017-02-21/156df93ca457df443d6005cb982a888d.ico?largePack=1

**Comment by nbtetreault** [comment]
J'ai soumis un favicon de 32 par 32 au lieu de 16 par 16. Tout le reste était déjà en place.

**Comment by mbarbeau** [comment]
Faudrait aussi l'ajouter dans le html pour que ça soit pris en compte sur les cellulaires.

**Comment by nbtetreault** [comment]
J'ai fait générer un "kit" sur realfavicongenerator.net [favicons.zip](https://github.com/infra-geo-ouverte/igo2/files/793441/favicons.zip)

Il y a déjà pas mal de fichiers d'icônes dans le [dossier favicon](https://github.com/infra-geo-ouverte/igo2/tree/master/src/assets/favicon) de igo2. Je ne sais pas si ils sont tous utiles ou par quoi ils ont été générés. Je vous laisse donc le soin de voir ce qu'il manque.

**Comment by frank79a** [comment]
Un commit des nouveaux icônes a été fait : #207
