### ISSUE TITLE
Interaction : recherche de couches, menu "Carte" et menu "Contexte".

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#162]

**Comment by gignacnic** [comment]
Il faudrait savoir que fait-on dans ce cas de recherche de couche ?
Exemple de cas 1 :
- On saisit un terme dans la barre de recherche 
- Les résultats s'affichent sous la barre 
- Un ou plusieurs résultats s'affichent dans les résultats de type couches sous la barre 
- Un usager sélectionne une couche,
À ce moment : 
1) Est-ce qu'elle s'affiche sur la carte (genre de "preview"), mais ne s'ajoute pas au contexte de carte ? On doit cliquer sur un bouton pour l'ajouter au contexte ?
2) Est-ce qu'elle s'affiche sur la carte et elle s'ajoute au contexte de carte ?
3) Est-ce que l'on doit cliquer sur un bouton pour l'afficher dans la carte et elle s'ajoute après au contexte de carte ?
Quelle est l'interaction avec le menu "carte" et la recherche de couches et le contexte, il y a une réflexion à avoir...

**Comment by mbarbeau** [comment]
4. Avoir un concept de couche temporaire : dernière couche sélectionnée qui est affichée. Dans la liste des couches dans l'onglet Carte, elle apparaît différemment des autres couches et a un bouton pour la rendre permanente. 
Combiné avec un bouton dans les résultats de recherche pour la rendre permanente directement.

**Comment by gignacnic** [comment]
Add in the release 0.11 within the context management and related to the Context API.
