### ISSUE TITLE
wms-time slider

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#196]
Intégrer le time slider au bas de la carte pour les couches WMS-Time, en attente de : https://github.com/angular/material2/issues/675#issuecomment-291787029

**Comment by gignacnic** [comment]
Ce qui est convenu de supporter dans le curseur temporel:
Sélection par 
- Une seule date (selon le format du wms-time)
- Entre deux dates (selon le format du wms-time)

Pouvoir gérer les temps de type (selon le format du wms-time):
- Année seulement
- Année-mois-jour seulement
- Année-mois-jour heure

- Avoir un bouton "play" pour faire le changement temporel automatiquement selon une période X.

**Comment by gignacnic** [comment]
DataPicker is now in Master of Angular/Material: https://github.com/angular/material2/blob/master/src/lib/datepicker/datepicker.md

**Comment by gignacnic** [comment]
@matrottier when you would have time, if you could look into the time slider feature, it would be a good add-on for our meteolorology data analysis.

**Comment by matrottier** [comment]
@gignacnic  
do we manage the timezone ?  
or we take only GMT time.   
managing the timezone can be tricky.
[there is no international standard that specifies abbreviations for civil time zones like CET, EST, etc.](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15)  
and put the offset timezone in the context is bad idea because we will have to change this every time change.   
https://xkcd.com/1883/

**Comment by gignacnic** [comment]
Yes, GMT it is. Try to look in the WMS Getcapabilities to get its time extent, such as: <Dimension name="time" units="ISO8601"/><Extent name="time" nearestValue="0">1980-01-01T05:00:00Z/2020-03-29T05:00:00Z</Extent>

**Comment by matrottier** [comment]
finally, the DataPicker's UI is always in user's local time.   
i didn't see a config to set the timezone.  
the UI will be in the user's local time and the request will be done in GMT time.

**Comment by matrottier** [comment]
what is the need for the type option 'time' (the user can set only the time. the date is now )  ?  
do we make the request with only the exact time ? 2017-09-09T15:23:00.000Z ?  
do we make the request for each day with the time ? 2017-09-09T15:23:00.000Z,2017-09-10T15:23:00.000Z  
do we make the request with only a range with a specfic range (ex: 1 hours by default)? 2017-09-09T15:23:00.000Z/2017-09-09T16:23:00.000Z

**Comment by gignacnic** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/99
