### ISSUE TITLE
image loading

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#199]
Avoir une image propre de chargement ou "loading" d'IGO2.

**Comment by frank79a** [comment]
Voici deux propositions pour l'image de chargement : une avec le logo d'IGO, et l'autre sans. Il y a deux versions pour chacune des propositions. La différence est au niveau de la vitesse de l'animation. Je peux vous fournir d'autres tailles d'images au besoin.

![icone-chargement-animation-01a](https://cloud.githubusercontent.com/assets/20860452/25953283/e4d92da6-3630-11e7-8771-69e14a9a3079.gif)
---------------------------------------
![icone-chargement-animation-01b](https://cloud.githubusercontent.com/assets/20860452/25953284/e4dc9374-3630-11e7-9abd-4af964849cf0.gif)

---------------------------------------

![icone-chargement-animation-03a](https://cloud.githubusercontent.com/assets/20860452/25953229/befe89d2-3630-11e7-8a7d-fa1c80b1eb57.gif)
---------------------------------------
![icone-chargement-animation-03b](https://cloud.githubusercontent.com/assets/20860452/25953230/beffc3d8-3630-11e7-9343-480dc9b7c79e.gif)

**Comment by cbourget** [comment]
This is nice! My personnal favorite and Nick's too is the slower one with the logo.

**Comment by gignacnic** [comment]
Super, le 4e c'est le meilleur oui !

**Comment by mbarbeau** [comment]
J'approuve pour le 4e. Le 2e, en plus petit, pourrait aussi être intéressant comme loading d'éléments dans l'application.

**Comment by frank79a** [comment]
Je vais faire une plus petite version du 2e. Est-ce que vous avez besoin que les images soient transparentes?
Et à quel endroit dois-je les déposer?

**Comment by gignacnic** [comment]
Oui il faudrait que ça soit transparente. J'imagine que tu pourrais les disposer dans le favicon, soit : src/assets/image *

**Comment by mbarbeau** [comment]
oui tu peux le mettre dans src/assets/images/ ça serait parfait.

**Comment by frank79a** [comment]
Les images de chargements ont été soumises. #214
