### ISSUE TITLE
Icone affichage des couches

### ISSUE THREAD

**Issue by stetou** [infra-geo-ouverte/igo2#201]
Je proposerais un oeil pour gérer l'affichage/masquage des couches au lieu des 2 petits carrés bleus

**Comment by cbourget** [comment]
That was our initial plan but the fontset we use doesn't have an open and closed eye.
See https://material.io/icons/

We're open to suggestions if you find something better in that fontset.

**Comment by stetou** [comment]
https://material.io/icons/#ic_visibility
https://material.io/icons/#ic_visibility_off

**Comment by cbourget** [comment]
Thank you for pointing out that these icons were added. We will proceed.

**Comment by pelord** [comment]
In addition to what Steve suggested, do you think it would be interesting to not unroll the legend menu when the user makes the layer visible? The unrolling of the legend prevents the user from making quick comparisons or "on / off" on the superposed layers.

**Comment by gignacnic** [comment]
Yes good idea, we can make default behavior as legend not unroll and in the application make it legend unroll behavior configurable. Good? @cbourget or @mbarbeau will integrate this.
