### ISSUE TITLE
Pourquoi un sous menu analyse temporelle

### ISSUE THREAD

**Issue by stetou** [infra-geo-ouverte/igo2#203]
Le menu principal devrait il me semble contenir les fonctions principales comme itinéraire et autes modules qu'on pourrait développer. Au lieu d'avoir un menu Analyse temporelle ce serait possible d'avoir un icone à côté de la couche lorsque la couche est "filtrable".

Aussi, changer les dates c'est loin d’être une "analyse" temporelle

**Comment by cbourget** [comment]
We're not sure if the layer list is the right place for that. We fear it'll end bloated if we add icons when:
    - The layer is filterable
    - The layer is of vector type and has a data table
    - etc.

What do you think?

Also, would you want that icon to redirect to another menu with the datepickers and stuff or to display the datepickers below the layer right inside the list?

Remember that the tool is still under development and that some features such as a time slider will be added.

**Comment by gignacnic** [comment]
En discutant avec certaines utilisateurs, ils apparaissaient aussi plus simple d'avoir un menu d'analyse temporelle et d'afficher seulement les couches ayant les éléments obligatoires pour une analyse avec le curseur temporel. À discuter près que tous les éléments du curseurs seront faits d'ici la mi-mai: https://github.com/infra-geo-ouverte/igo2/issues/196

**Comment by gignacnic** [comment]
Ce problème a été atténué dans la prochaine version d'IGO2 reliée à la libriarie Igo2Lib. Un icône sera disponible pour favoriser la navigation entre les outils à gauche du panneau. À voir dans le prochain release.
