### ISSUE TITLE
Embacle ..... demo.boundless error

### ISSUE THREAD

**Issue by stetou** [infra-geo-ouverte/igo2#204]
Lorsqu'on ouvre le contexte Embacle on a une erreur dans la console car cette requete ne fonctionne pas
http://demo.boundlessgeo.com/geoserver/wms?request=GetCapabilities&service=wms&version=1.3.0

**Comment by gignacnic** [comment]
Oui, boudless a fermé son service. Je l'ai enlevé, vide ta cache pour voir.
