### ISSUE TITLE
add metadata url layer and trigger

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#205]
For a layer, when a *_dataurl_href is defined in the Getcapalities, include an icon somewhere and in the UI to get more information on its metadata using this link as trigger. If it is a *_dataurl_format = 'text/html', open this html web page in another panel in the browser. Different behavior can be done for different *_dataurl_format.

**Comment by gignacnic** [comment]
@pelord: how you see this feature in the app, this dataurl should be in the map panel for each layer:
1- Option on click on the title of the layer to open URL
2- Option using the gear
3- Add "I" button

**Comment by pelord** [comment]
I think the easiest way is to create a link on the layer's title (option 1) opening à new tab (blank target).

**Comment by gignacnic** [comment]
Yes, that is I think too. What do you think @mbarbeau ?

**Comment by gignacnic** [comment]
Finally, option 2 was better in terms of look-and-feel instead of the option 1, see this image. @pelord would you prefer the option 2 gear (2 click to get metadata) or adding the "I" beside the gear instead (one click to get metadata) ?
![capture du 2017-06-01 10-58-24](https://cloud.githubusercontent.com/assets/5321940/26686016/bddd27ea-46b9-11e7-9158-b802be1e6cad.png)

**Comment by pelord** [comment]
Thanks, it's seem to be a good alternative. Afterwards, maybe option # 1 was probably surcharging the visual looking of the interface. 

I think the "I" as you propose in your screenshot is really nice. Go on!

**Comment by pelord** [comment]
@gignacnic 
 Is it mandatory to fill the metadata section into the context.json to trigger the url?


      "metadata": {
        "url": "www.perdu.com",
        "extern": true
      }

**Comment by gignacnic** [comment]
yes, but if you use mapserver, it will get the wms_dataurl_href if provided in getcapabilities. This last feature will be added in the release coming in.
