### ISSUE TITLE
Quel bénéfice d'utiliser igo2 par rapport à un install d'Angular + Openlayer fait soi-même?

### ISSUE THREAD

**Issue by seinecle** [infra-geo-ouverte/igo2#238]
Ce projet est très intéressant mais dans son readme, on ne comprend pas ce qu'il apporte de plus par rapport à un install manuel de angular et openlayer?

**Comment by gignacnic** [comment]
En somme, ce projet est un assemblage (framework) d'OpenLayers 4 avec Angular6-Material déjà développé, intégré, testé et avec des fonctionnalités de plus qui n'existent pas dans OpenLayers, comme imprimer une carte en GeoTiff-PDF avec la légende + échelle, d'ajouter des couches WMS par un catalogue, de partager une carte par un lien, de produire un itinéraire sur la carte, etc. Comme comparatif, lorsqu'OpenLayers 2 était la dernière version, geoext agissait comme projet d'assemblage. Maintenant IGO2 peut être considéré comme projet d'assemblage pour OpenLayers avec Angular 6 et Material.
Ce projet permet de ne pas recoder toutes les fonctionnalités dans Angular avec OpenLayers et comme il est open source, il peut être amélioré, réutilisé et modifié gratuitement. Toute contribution est évidemment appréciée. Son code source est supporté par des employées de l'administration publique du Québec au Canada. IGO2 peut être utilisé et déployé dans n'importe quel contexte ailleurs dans le monde (avec des cartes et services Web d'OpenStreetMap par exemple). Ce projet est aussi internationalisé en langue anglaise et française, puis suit les standards Web OGC dans OpenLayers, comme les WMS, WMTS et WFS.
Vous pouvez aller consulter ces démos : https://github.com/infra-geo-ouverte/igo2-lib#demo ou utiliser ce lien direct vers le projet de données ouvertes du Québec qui contient un ensemble complet des fonctionnalités intégrées : https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/ 
En complément, voici une réponse que j'avais faite sur Stackoverflow et qui était connexe à ta question, c'est à dire de réutiliser un projet existant (IGO2) au lieu de recommencer à zéro avec un nouveau projet OpenLayers+Angular5 : https://stackoverflow.com/a/49080929
N'hésites pas si tu as besoin d'autres informations.

**Comment by seinecle** [comment]
So, a bit like Jhipster in terms of purpose (scaffolding). Thx!

**Comment by pelord** [comment]
Est-ce que l'ont peut fermer cet "issue" ?
