### ISSUE TITLE
Re-enable query params 1.0.0-alpha.1

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#258]
**Please tell us about your environment:**

* **Igo Version:**
1.0.0-alpha.1
* **Node:**

Re-enable adding layers by url as in master

https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/?context=mtq&wmsUrl=%2Fapis%2Fws%2Fswtq&layers=toponymie_structure

**Comment by mbarbeau** [comment]
1) Manque le param search=
2) Je crois que le param tool= devrait ouvrir le menu ?

**Comment by pelord** [comment]
Exact. tool= devrait sélectionner le tool, p-etre pas l'ouvrir. a toi de voir.

Faut pas oublier le "directions" aussi pour les itinéraire.

**Comment by mbarbeau** [comment]
Selon les tests de https://github.com/infra-geo-ouverte/igo2/wiki/URL-params-to-control-app-behavior

- [ ] 1) Ne fonctionne pas en tout temps
- [ ] 5) tool= Sélectionner l'outil (options pour l'ouvrir ou pas ?)
- [ ] 6) Non fonctionnel
- [ ] 7) Non fonctionnel
