### ISSUE TITLE
Icone pour fond de carte

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#282]
- Utiliser l'icone de fond de carte (actuellement utilisée dans le cas mobile, voir screen shot) dans tous les cas.
- uniformiser taille des icônes et leur couleur en bas de carte
![fondCarte](https://user-images.githubusercontent.com/32843565/64961641-f416af00-d863-11e9-8987-e6fc551b37f8.PNG)

**Please tell us about your environment:**

* **Igo Version:** 1.0

* **Node:**

**Comment by mbarbeau** [comment]
Fait

**Comment by josee666** [comment]
?? Moi j'aimais bien avoir un petit apercu du fond de carte en mode ordinateur plutôt qu'un icone 
![image](https://user-images.githubusercontent.com/32003632/65263144-ecf8d680-dad9-11e9-82cb-d119baf0c59f.png)

**Comment by pelord** [comment]
Je préfère l'icone.

**Comment by VP08** [comment]
TEst Icone ok
par contre l'image dans le premier carré est décallé par rapport au contour...
![icone fond de carte](https://user-images.githubusercontent.com/32843565/65547513-9c251b80-dee7-11e9-9be4-c217a0124f82.PNG)
