### ISSUE TITLE
Menu paramètres de recherche à optimiser visuellement

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#283]
- trop d'espacements entre les options

- le bleu des cases à cocher n'est pas le même que le reste

- iCherche ou ICherche?

- dans Type de résultat entre iCherche et Territoire : MRC ou  mrc?

- nom des options: iCherche Québec et Territoire (géocodage inversé) à discuter en fonction du choix du nom des API

![param](https://user-images.githubusercontent.com/32843565/64963193-ddbe2280-d866-11e9-8221-b7ef644d68ed.PNG)

**Please tell us about your environment:**

* **Igo Version:** 1.0

* **Node:**

**Comment by mbarbeau** [comment]
1) Fait
2) Le bleu c'est la couelur "accent" du thème. Peut être modifié facilement
3) iCherche -> À Changer
4) Je crois que MRC doit être en majuscule. -> Rien à changer
5) À faire

**Comment by VP08** [comment]
4. voir mrc dans menu Territoire

**Comment by VP08** [comment]
mrc dans menu Territoire (Géocodage inversé) n'est pas corrigé?

**Comment by VP08** [comment]
ok MRC corrigé
