### ISSUE TITLE
fonctionnement du I (information)

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#284]
- [ ]  le texte d'aide lorsque on passe la souris sur le I mentionne "Attributions" ça n'Est pas clair, "Information" plutôt? ->transféré dans #323
- [x]  lorsque ouvert le texte embarque sur l'échelle (le mettre toujours au dessus du I comme version mobile?
- [ ]  enlever mention /IGO2 (ne s'applique par au couches..., mentionnée dans l'a propos à la place); si on la garde, remplacer par icone IGO; sinon trouver où mettre le logo IGO à une autre place -> à gérer par contexte
- [x] l'icone est entourée de bleu lorsqu'on l'a cliquée (?) disparaît au bout d'un moment?

**Please tell us about your environment:**

* **Igo Version:** 1.0

* **Node:**

**Comment by mbarbeau** [comment]
lorsque ouvert le texte embarque sur l'échelle (le mettre toujours au dessus du I comme version mobile? -> Fait
