### ISSUE TITLE
outil mesurage/tableau Sommes de la sélection

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#285]
- le panneau des Sommes de la sélection n'a pas la même police que le reste
- pourquoi Longueur plutôt que Distance ?
-  doit-on absolument répéter les termes Longueur et Superficie?

**Please tell us about your environment:**

* **Igo Version:** 1.0

* **Node:**

![sommeSelect](https://user-images.githubusercontent.com/32843565/64965376-d731aa00-d86a-11e9-921c-79368abe440d.PNG)

**Comment by cbourget** [comment]
Je suis d'accord avec ces points. L'outil a été réalisé selon des specs définies à la FADQ donc je vais joindre @danlav01 à cette conversion.

**Comment by danlav01** [comment]
La demande que nous avions était celle de modifier le terme «Longueur» pour «Distance», ce qui n'a visiblement pas été fait dans le formulaire de «Sommes de la sélection».  On peut donc changer «Longueur» pour «Distance». Quant à la répétition des termes, nous sommes tout à fait d'accord pour ne pas les répéter. Enfin, pour ce qui est de la fonte, il n'y a effectivement aucune raison pour qu'elle soit différente. On peut donc la changer. 
Si vous voulez qu'on fasse les changements, il serait préférable pour nous de les faire après la «Release» puisque notre version n'est pas à jour. Sinon vous pouvez faire le changement pour la «Release». À vous de voir. Merci beaucoup!

**Comment by mbarbeau** [comment]
corrigé https://github.com/infra-geo-ouverte/igo2-lib/commit/9ec9063cb2d14794a8be1086fff98b6d95469b84

**Comment by VP08** [comment]
ok
