### ISSUE TITLE
nom Mesurage

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#286]
- revoir le nom de l'outil "Mesurage"
- simplement Mesure?
- dans le panneau de l'outil, la première option serait "Activer/désactiver outil" au lieu de Mesurage?

**Please tell us about your environment:**

* **Igo Version:**
1.0
* **Node:**

**Comment by mbarbeau** [comment]
corrigé infra-geo-ouverte/igo2-lib@9ec9063
