### ISSUE TITLE
icone ouverture expansion panel

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#287]
- pourquoi noir? mettre bleu comme autres icônes bas de page?
- pouquoi carré blanc plus gros? uniformiser taille des icônes
- pourquoi collé au cadre quand les autres icônes sont décalées du bord? (marge présente si on ouvre le menu par contre...)

**Please tell us about your environment:**

* **Igo Version:** 1.0

* **Node:**

**Comment by mbarbeau** [comment]
pouquoi carré blanc plus gros? uniformiser taille des icônes -> Fait
pourquoi collé au cadre quand les autres icônes sont décalées du bord? (marge présente si on ouvre le menu par contre...) -> Fait

**Comment by PhilippeLafreniere18** [comment]
Mettre bleu --> Fait

**Comment by VP08** [comment]
je ne le vois plus, je ne peux pas valider
