### ISSUE TITLE
texte de l'option Filtre sur Couches caché

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#288]
Dans l'onglet Couches; le texte "Filtre" est à moitié caché sous la barre bleue lorsqu'on clique pour taper 
![filtre](https://user-images.githubusercontent.com/32843565/64981751-ac574e00-d88a-11e9-954d-2ac2084cbf85.PNG)

**Please tell us about your environment:**

* **Igo Version:** 1.0

* **Node:**

**Comment by mbarbeau** [comment]
Corrigé

**Comment by VP08** [comment]
me semble toujours caché?

**Comment by VP08** [comment]
ok
