### ISSUE TITLE
panneau des informations des features sélectionnés ne présente pas asser d'information

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#289]
**Please tell us about your environment:**

* **Igo Version:**
1.0 beta.geom...

Lors de la sélection d'une feature on ne voit plus asser d'informations.

Avant nous pouvions présenter dans le tableau beaucoup plus d'informations. La nouvelle version est trop limitative sur l'espace de présentation des informations, il faudrait agrandir...

Exemple :
Avant:

![image](https://user-images.githubusercontent.com/32003632/64982177-8a120000-d88b-11e9-94ab-d4fc64df93b4.png)

Maintenant avec v.1:
![image](https://user-images.githubusercontent.com/32003632/64982159-82eaf200-d88b-11e9-9758-93ff73c166cf.png)

**Comment by josee666** [comment]
NB: Lorsque les info sont présentées en GML le panneau ouvre + grand que dans le format html...

**Comment by pelord** [comment]
Je vous rappelle dans dans la version 1.0.0, il y a aussi la méthode d'appel des getinfo, combinant la geometrie gml et le résultat html.

il faut utiliser le queryFormat `htmlgml2`

https://github.com/infra-geo-ouverte/igo2-lib/blob/1dfe5cac4c4c95967ac9406da5a13535a03fdc89/demo/src/app/geo/query/query.component.ts#L88

**Comment by josee666** [comment]
ok pour le param queryFormat  htmlgml2 👍 mais le panneau qui présente les info lorsqu'on est configuré en html (html ou htmlgml2) devrait ouvrir plus grand pour permettre de présenté plus d'information. Il semble avoir une grandeur fixe lorsqu'on est en html (plus petite qu'un grand gml...) Il faudrait que le panneau sorte plus.

**Comment by mbarbeau** [comment]
Corrigé, prend maintenant la pleine hauteur comme en GML
