### ISSUE TITLE
ajout groupe via catalogue -ordre présentation VS empilement des couches problème

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#291]
**Please tell us about your environment:**

* **Igo Version:**
1.0 

Lors de l'ajout d'un groupe de couche dans le catalogue à l'aide du + il y a un problème dans l'ordre des couches qui ne respectent pas la logique de visualisation en fonction de l'empilement de IGO soit plus bas est en dessous. Apres l'ajout du groupe dans le panneau les couches ne sont pas dans l'ordre présentées visuellement, visuellement c'est ok mais dans l'ordre c'est inversé par rapport a se qu'on voit.

exemple: zommer (16) dans un secteur, catalogue, inventaire forestier, + ajouter groupe peuplement. Apres ajout, le visuelle est bon on visualise dans la carte selon:
étiquette
contour
couleur (plein)

mais se qui nous est présenté est inversé soit:
couleur(plein)
contour
étiquette

![image](https://user-images.githubusercontent.com/32003632/64986043-3b1c9880-d894-11e9-9641-9dff9d58ca58.png)

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2/issues/320
