### ISSUE TITLE
Afficher les coordonnées: Affichage en lat,lon au lieu de lon,lat?

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#292]
when you do a right click on map -> afficher les coordonées
you get: -72.86089897155762, 47.428871143527005

1- round that number
2- invert for lat, lon 

get result: 
47.428871, -72.860899

**Please tell us about your environment:**

* **Igo Version:1.0**

**Comment by mbarbeau** [comment]
1) J'ai limité à 6 décimales
2) Inverser les coordonnées demande un peu plus de travail pour garder la cohérence dans toute l'application. Il doit aussi avoir une concertation avec les autres partenaires.

**Comment by pelord** [comment]
sera traité dans https://github.com/infra-geo-ouverte/igo2/issues/782
