### ISSUE TITLE
tool - tooltips stick on gui

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#293]
Only from the start menu, when you click on a tool at the same time(important) the tooltip appear, the tooltips stick in the interface.

**Please tell us about your environment:**
Chrome 76.0
* **Igo Version: 1.0**

![image](https://user-images.githubusercontent.com/32003632/65054108-09124180-d93b-11e9-9367-55a5ccf10b13.png)

![image](https://user-images.githubusercontent.com/32003632/65054021-e5e79200-d93a-11e9-8dd6-6bfb6e93ce79.png)

**Comment by mbarbeau** [comment]
Retrait des tooltips sur le start menu. Il sert à rien puisque c'est la même chose que le titre.
