### ISSUE TITLE
Test internet explorer

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo2#295]
**Please tell us about your environment:**

Windows 8
Internet Explorer 11.0.9600.19432

Igo Version: alpha 1.0

- [x] Barre de recherche plus courte, mauvais alignement lors de la recherche
![image](https://user-images.githubusercontent.com/9534827/65065932-61543e00-d951-11e9-80af-f5a6f36ec55b.png)

- [ ] Menu table inférieur non visible
![image](https://user-images.githubusercontent.com/9534827/65065988-8183fd00-d951-11e9-8e05-79e986bccfed.png)

- [x] Icône de localisation non alignée
![image](https://user-images.githubusercontent.com/9534827/65066005-88127480-d951-11e9-9a37-8bec2d6a258d.png)

- [ ] La flèche d'attribution disparaît lorsque l'on bascule sur OSM. Elle ne revient pas après (Chrome aussi)
![image](https://user-images.githubusercontent.com/9534827/65065975-7a5cef00-d951-11e9-81c8-dbf05a5ede16.png)

- [ ] Positionnement GPS ne fonctionne pas
- [x] Attributions et icône de fond de carte sont cachés par l'ouverture du menu
![image](https://user-images.githubusercontent.com/9534827/65073278-8c925980-d960-11e9-98cf-dd36a410fe08.png)

- [x] On doit ouvrir le panneau d'itinéraire pour "activer" l'url d'itinéraire (Chrome aussi)
Exemple: https://testgeoegl.msp.gouv.qc.ca/igo2/acrigeo/?tool=directions&routing=-71.27652886,46.77236699;-74.76526224,46.0053315

- [x] Le getInfo ne fonctionne pas

Sinon pour ce qui reste, ça semble bien aller ;(

**Comment by PhilippeLafreniere18** [comment]
1. Résolu 
2. Non résolu
3. Résolu
4. Problème général avec OSM (Résolu)
5. Non résolu
6. Résolu
7. Non résolu
8. Résolu

**Comment by mbarbeau** [comment]
7) Est résolu dans un autre issue

**Comment by mikesmichael** [comment]
2- Le menu du panneau a été retiré alors ne peut pas être testé sur cette version
4- Un autre issue a été créé pour le problème d'attributions OSM
5- Positionnement GPS dans IE est contrôlé par les règles d'active directory sur le partage de l'emplacement (ne fonctionne pas non plus sur google map)
