### ISSUE TITLE
Impression: Symbole de la légende ne s'affiche pas pour certaines icônes

### ISSUE THREAD

**Issue by mbarbeau** [infra-geo-ouverte/igo2#305]
- Le symbole de la légende ne s’affiche pas lorsque c’est un symboles spéciales
- ~Description : seulement une ligne est acceptée~ #385

**Comment by pelord** [comment]
Ce serait bien d'ajouter aussi la barre d'échelle à l'impression.

**Comment by ameliebernier** [comment]
À évaluer, est-ce un bug mapserver?

**Comment by ameliebernier** [comment]
Possible lien avec #387
