### ISSUE TITLE
Porposition : catégoriser les résultats d'iCherche

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#309]
La recherche de lieu est plus complexe et les données sont moins structurées, ce qui rend plus difficile la pondération des résultats et peut parfois mener à des incohérence.

Les résultats de iCherche pourraient apparaître dans deux catégories différentes (noms exacts à définir) : iCherche "Adresse" (adresses, code postaux, municipalités, régions, MRC...) et iCherche "Lieux" (tous les autres lieux : bornes, toponymes, écoles, entreprises...).

![image](https://user-images.githubusercontent.com/45005853/65154081-e2b2db80-d9f8-11e9-8669-18273454a6e5.png)

**Comment by pelord** [comment]
Faut donc faire un appel par type de recherche?

**Comment by mbarbeau** [comment]
Ne sera pas fait pour l'instant.
