### ISSUE TITLE
Tests Firefox

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#310]
- [x] clic droit (afficher coordonnées) sur le carte ne fonctionne pas (affiche menu du navigateur web Afficher image, Enregistrer image...)

- [x] icone expand panel invisible (s'affiche temporairement selon les fonds de carte...), non cliquable
- [x] espacement entre les cases à cocher et le texte est trop mince dans panneau Mesurage

- [x] Le getInfo ne fonctionne pas  (le panneau des entitées trouvées s'affiche temporairement lorsque qu'on change de fond de carte ou de couches)

![firefox](https://user-images.githubusercontent.com/32843565/65153532-e8f48800-d9f7-11e9-8ba9-afa2891b3382.PNG)

**Please tell us about your environment:**
Firefox 56.0

* **Igo Version:** 1.0

* **Node:**

**Comment by PhilippeLafreniere18** [comment]
1. Résolu --> question de version du browser (marche sur la récente)
2. Résolu
4. Résolu
