### ISSUE TITLE
Indicateur visuel quand les couches ne sont pas visibles à l'échelle actuelle de la carte

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#311]
Quand une couche n'est pas visible parce que l'échelle actuelle de la carte l'empêche, il faudrait un indicateur visuel dans l'onglet carte et dans les résultats de recherche (ex.: mettre le nom de la couche en grisé...)

**Comment by VP08** [comment]
dans l'onglet Carte/Couches l'oeil est grisé, non?

**Comment by ameliebernier** [comment]
Ah oui c'est vrai. Mais quand on ajoute une couche à partir de la recherche et qu'on ne la voit pas apparaître, on a l'impression qu'il ne se passe rien

**Comment by VP08** [comment]
suggestion: basculer vers Carte/Couches quand on ajoute une couche (via catalogue ou recherche)

**Comment by mbarbeau** [comment]
#301

**Comment by josee666** [comment]
Le bascule automatique sur ajout d'une couche dans le catalogue avait été discuté mais non retenu car il est intéressant d'être dans le catalogue et de pouvoir faire plusieurs clic et d'ajouter plusieurs couche. Si on bascule automatiquement on ne pourra plus faire cela.
idée: mettre la poubelle en gris pale lorsque non visible a l'échelle actuelle

**Comment by ameliebernier** [comment]
Mettre une confirmation que la couche a été ajoutée (toast) ?

**Comment by pelord** [comment]
Je trouve que ca ferait trop. La poubelle est suffisante a mon avis.

**Comment by ameliebernier** [comment]
Je ne trouve pas que la poubelle ait un lien avec la visibilité de la couche, ce n'est pas clair pour un utilisateur.... le bouton aura juste l,air désactivé

**Comment by pelord** [comment]
ca dépends de quoi on parle. 
si on parle de "confirmation que la couche a été ajoutée (toast) ?", la poubelle suffit.
si on parle d'une couche ajouté non visible a l'échelle actuelle, le toast devient intéressant.

**Comment by ameliebernier** [comment]
Bien sur en lien avec la visibilité...

Je pense que le fonctionnement pour l'ajout (plus) /retrait (poubelle) de couche est clair, c'est juste quand on ajoute une couche pas visible (objet de ce issue)

**Comment by pelord** [comment]
Corrigé version 1.1

Dans catalog ou la recherche de couches.

![image](https://user-images.githubusercontent.com/7397743/68711290-57247980-0567-11ea-915c-09501d18dd07.png)
