### ISSUE TITLE
le symbole loading ne s'affiche plus

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#312]
Avant il y avait un petit rond qui tournait dans le coin en haut a droite lorsque la couche se chargeait, ce dernier n’apparaît plus.

**Please tell us about your environment:**
 Browser :chrome 76.0
* **1.0:**

**Comment by mbarbeau** [comment]
Fix dae5a910b97793124b7284a960bdcad9255e71c3
