### ISSUE TITLE
partage de carte- certaines options ne se partagent pas

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#314]
1- Les couches 'allumées' ou éteintes ne sont pas conservées lors du partage. Si j'ai ajoutées 3 couches éteintes et que je partage, Elles seront allumées dans le résultat de partage

2- Idem pour la transparence et l'ordre des couches qui n'est pas conservé dans le résultat de partage

3- les filtres

**Please tell us about your environment:**
 Browser :chrome 76.0

* **Igo Version:**
1.0.0

**Comment by mbarbeau** [comment]
Mettre un avertissement à l'utilisateur

**Comment by pelord** [comment]
1 - A venir.
2 et 3- Voir l'image ici bas

![image](https://user-images.githubusercontent.com/7397743/69298340-85dfc700-0bdb-11ea-961c-f2a77438df26.png)
