### ISSUE TITLE
Affichage des résultats de recherche pour les découpages administratifs

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#317]
Il serait possible d'améliorer lareprésentation des découpages adminstratifs (municipalités, mrc, régions...) dans les résultats de recherche pour aider l'utilisateur. Actuellement ce n'est pas constant d'un type à l'autre.

Par exemple quand on cherche une municipalité, le nom de la MRC à laquelle elle appartient s'inscrit à côté mais ce n'est pas toujours aidant : 

![image](https://user-images.githubusercontent.com/45005853/65340796-03b43180-db9d-11e9-9ffd-e8e22a3758ce.png)

De plus je pense que les MRC sont beaucoup moins connue que les régions administratives. Le nom de la région aiderait plus l'utilisateur.

Quand plusieurs municipalités ont le même nom on pourrait ajouter la désignation :

![image](https://user-images.githubusercontent.com/45005853/65340837-162e6b00-db9d-11e9-908e-364d9cb508ac.png)

Pour les MRC on écrit la mention MRC à côté du résultat, mais pour les régions et les municipalités on ne le fait pas

![image](https://user-images.githubusercontent.com/45005853/65340931-40802880-db9d-11e9-8c5b-7f9395ac4835.png)

![image](https://user-images.githubusercontent.com/45005853/65340957-4d048100-db9d-11e9-833b-809454d072e7.png)

![image](https://user-images.githubusercontent.com/45005853/65341002-63124180-db9d-11e9-90e1-9d115fe9642e.png)

**Comment by ameliebernier** [comment]
Aussi je me demande si de façon générale on ne devrait pas inscrire le type de résultat de recherche pour chaque résultat? Ex,: Région administrative, MRC, Municipalité

**Comment by mbarbeau** [comment]
Pas un bug de IGO. Transféré à iCherche
