### ISSUE TITLE
catalogue layer order

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#320]
Browser : chrome 76.0
Igo Version: 1.0.0

the order of the groupe/layer in catalogue doesn't respect the order of the service.
before:
![image](https://user-images.githubusercontent.com/32003632/65512994-55fc9780-dea8-11e9-9eba-4cdac92c488d.png)

Now, new version:
![image](https://user-images.githubusercontent.com/32003632/65513031-6f054880-dea8-11e9-92fc-9a3bbd6b2f9e.png)

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/424

**Comment by mbarbeau** [comment]
Corrigé
