### ISSUE TITLE
Outil d'exportation: Permettre l'extraction des couches téléchargeables

### ISSUE THREAD

**Issue by matrottier** [infra-geo-ouverte/igo2#327]
**Please tell us about your environment:**
Chromuim Version 76.0.3809.100 (Build officiel) Built on Ubuntu , running on Ubuntu 18.04 (64 bits

* **Igo Version:**
1.0

Avec un layer du style WMS/WFS: 
```
{
        "name": "Trajets",
        "visible": false,
        "id": "filtre_trajet",
        "title": "Trajets",
        "sourceOptions": {
          "type": "wms",
          "optionsFromCapabilities": true,
          "url": "/ws/tracking.fcgi",
          "params": {
            "layers": "tracking_all_trajet_l_v",
            "version": "1.3.0",
            "feature_count": 100
          },
          "paramsWFS":{
            "featureTypes": "tracking_all_trajet_l_v",
            "maxFeatures": 10000,
            "version": "2.0.0",
            "outputFormat": "GEOJSON_utf8"
          },
          "queryable": true,
          "queryFormat": "gml2"
          }
      }
```
L'outil export ne permet pas de sélectionner le layer, mais le petit bouton téléchargement sur le layer est présent.  
serait intéressant de permettre l'export avec l'outil.

**Comment by pelord** [comment]
Il y a une balise download . voir balise download.interface.

Est-ce possible de croise les 2 options méthodes?

**Comment by pelord** [comment]
C'est fait dans laversion 1.5.0

**Comment by ameliebernier** [comment]
Terminé ou pas? @pelord il reste quelque chose à compléter?
