### ISSUE TITLE
Filtre temporel: Ajout d'un ti-piton pour réinitialiser les valeurs

### ISSUE THREAD

**Issue by matrottier** [infra-geo-ouverte/igo2#328]
**Please tell us about your environment:**
Chromuim Version 76.0.3809.100 (Build officiel) Built on Ubuntu , running on Ubuntu 18.04 (64 bits

* **Igo Version:**
1.0

Ajouter un ti-piton reset pour le filtre temporel.  
retour au min/max initial

**Comment by pelord** [comment]
voir 

- infra-geo-ouverte/igo2-lib#265
- infra-geo-ouverte/igo2-lib#411


A déja été mergé dans le master pour le type année

**Comment by matrottier** [comment]
Good! je vais reprendre le flambeau pour qu'il soit présent sur un type datetime au minium

**Comment by matrottier** [comment]
Après analyse, je suis arrivé à la conclusion que le filtre temporel devrait être reconstruit. (de là ma perte de motivation pour ajouter le ti-piton =p )  
Permettre la combinaison de filtre temporel et OGC fait parti des demandes au MSP.  
Je suppose que le "ti-piton" sera alors ajouté.

**Comment by pelord** [comment]
Je pense la même chose.

**Comment by ameliebernier** [comment]
Relié aux autres améliorations à faire pour les filtres : https://github.com/infra-geo-ouverte/igo2/issues/396 et https://github.com/infra-geo-ouverte/igo2/issues/503

**Comment by ameliebernier** [comment]
Le problème est quand même présent dans la version OGC du filtre donc c'est toujours d'actualité
