### ISSUE TITLE
changeur de style - clarifier pour utilisateur

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#331]
* **Igo Version:1.0.0**

1- Clarifier si est disponible. A l'heure actuelle rien n'indique que l'option de changer de style est disponible ou non sur une couche, on doit ouvrir la légende pour comprendre qu'il y a plusieurs style disponible sur cette couche. Il faudrait ajouter un icone ou quelque chose dans les options qui dit visuellement que le style peux être changer, sans avoir a ouvrir la légende pour voir que le style peux être changé. Exemple: 
![image](https://user-images.githubusercontent.com/32003632/66068807-43bfd080-e51c-11e9-9ac6-7c5f997a4cc8.png)

2- Clarifier la flèche qui ouvre les styles disponibles. Elle est très petite et comme tout est blanc on ne comprend pas du premier coup que ça va avec le nom. Idée: plutôt qu'une petite flèche mettre un icone et laisser engrisé ou mettre encadré...
![image](https://user-images.githubusercontent.com/32003632/66069081-add87580-e51c-11e9-9373-fc4877acd635.png)

3- Default/légende. Lorsqu'on reviens au default, il n'y a plus de légende associée...

**Comment by hugbe8** [comment]
L'indication de la disponibilité vient avec la flèche qui ouvre les styles. Pas de flèches pas de choix.

**Comment by hugbe8** [comment]
on y reviendra après usage s'il y a d'autre commentaire qui vont dans le même sens.

**Comment by pelord** [comment]
La version dans le master igo2-lib clarifie cette issue.

**Comment by pelord** [comment]
Version 1.1 @josee666
