### ISSUE TITLE
pas d'info bulle sur couches dans Catalogue

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#336]
pas d'info bulle sur les couches dans le Catalogue: si le nom de la couche est trop long on ne peut pas les différencier

**Please tell us about your environment:**

Windows, Chrome Version 77.0.3865.120 (Build officiel) (64 bits)
* **Igo Version:** 1.0 

* **Node:**

![image](https://user-images.githubusercontent.com/32843565/67209546-8ff88500-f3e5-11e9-9e36-bdc73c7e0016.png)

**Comment by pelord** [comment]
Corrigé version 1.1
