### ISSUE TITLE
Filtre temporel: désactiver n'arrête pas la lecture

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#337]
Lorsqu'on désactive le filtre temporel alors qu'il était en train de "jouer" il ne s'arrête pas, n'est pas désactivé...

**Please tell us about your environment:**
 windows Chrome Version 77.0.3865.120 (Build officiel) (64 bits)

* **Igo Version:**
1.0
https://infra-geo-ouverte.github.io/igo2/

* **Node:**

**Comment by pelord** [comment]
bien vu.

**Comment by pelord** [comment]
Sera corrigé par 

infra-geo-ouverte/igo2-lib#478

**Comment by pelord** [comment]
Intégré dans la version "master" d'igo2-lib. Sera intégré au prochain release, 1.1 probablement.
