### ISSUE TITLE
Icône d'information manquant

### ISSUE THREAD

**Issue by davidboucher-28** [infra-geo-ouverte/igo2#338]
![image](https://user-images.githubusercontent.com/53181729/67218811-ffc23c00-f3f4-11e9-920e-9b298fdf7dba.png)

L'icone n'apparaît pas lorsqu'on ajoute la couche par la recherche ou le catalogue.

**Please tell us about your environment:**

Google Chrome
* **Igo Version:**
1.0

* **Node:**

**Comment by pelord** [comment]
Je n'ai pas ce problème avec la version 1.0.0

Voir

https://infra-geo-ouverte.github.io/igo2/?wmsUrl=https:%2F%2Fgeoegl.msp.gouv.qc.ca%2Fapis%2Fws%2Figo_gouvouvert.fcgi&layers=(evenements:igoz18)

Les avertissements routiers est une couche ajoutée du catalogue.

**Comment by mbarbeau** [comment]
Pas un bug de IGO
