### ISSUE TITLE
catalogue - permettre l'ajout de catalogue en version 1.1.1

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#341]
Pouvoir mettre un catalogue qui n'est pas en version 1.3.0

* **Igo Version:**
1.0

**Comment by josee666** [comment]
NB: En version 1.1.1 param SRS vs CRS

**Comment by pelord** [comment]
Tu as raison. On peut appeler le catalogue dans la version que nous voulons. par contre, la couche est appelée en 1.3.0 lorsqu'elle est ajoutée du catalogue.

**Comment by pelord** [comment]
{
        "id": "yourId",
        "title": "yourTitle",
        "url": "yourUrl",
        "version": "1.1.1"
      },

**Comment by pelord** [comment]
En fait, il faut ajouter le SRS/srs dans "queryParams" pour les version < 1.3.0

```
{
"id": "yourId",
"title": "yourTitle",
"url": "yourUrl",
"version": "1.1.1",
"queryParams": {
    "srs": "EPSG:3857"
    }
}
```

Regarde https://github.com/infra-geo-ouverte/igo2-lib/pull/480
