### ISSUE TITLE
icone différente pour ajout de catalogue

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#343]
Signaler à l'utilisateur qu'il ajoute potentiellement BEAUCOUP de couches d'un coup.
icone différente pour ajout de catalogue? titre catalogue en gras? message?

**Please tell us about your environment:**

* **Igo Version:** 1.0

* **Node:**

**Comment by cbourget** [comment]
Il y a une option pour obliger l'utilisateur à ouvrir le groupe avant de l'ajouter. Autrement, l'icône reste gris et est inactif. L'utilisateur voit donc tout ce qui sera ajouté Est-ce que ça peut répondre au besoin?

**Comment by VP08** [comment]
oui ça serait déjà très bien.

**Comment by cbourget** [comment]
L'option s'appelle "toggleCollapsedGroup" et il faut la mettre à false dans les options du catalogue.

**Comment by pelord** [comment]
```
   {
     "name": "catalog",
     "options" : {
      "toggleCollapsedGroup": false
     }
   }
```

ne semble pas avoir d'effet

**Comment by cbourget** [comment]
C'est une option du catalogBrowser et non de catalog (anciennement catalogLibrary).

**Comment by pelord** [comment]
```
   {
     "name": "catalogBrowser",
     "options" : {
      "toggleCollapsedGroup": false
     }
   }
```

Merci. ca fonctionne.
