### ISSUE TITLE
Associer l'ajout de couches par cataloguage avec les service de recherche pour complémenter les propriétés disponibles pour IGO2

### ISSUE THREAD

**Issue by mbarbeau** [infra-geo-ouverte/igo2#344]
Associer l'ajout de couches par cataloguage avec les service de recherche pour complémenter les propriétés disponibles pour IGO2

**Comment by ameliebernier** [comment]
Les couches devraient avoir les mêmes attributs, qu'elles proviennent du catalogue, de la recherche ou des contextes.

**Comment by pelord** [comment]
Complété et intégré dans la branche next. Fera parti de la prochaine version.

**Comment by pelord** [comment]
@mbarbeau  On ferme l'issue?

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/583
