### ISSUE TITLE
Barre d'outils d'une couleur distincte

### ISSUE THREAD

**Issue by VP08** [infra-geo-ouverte/igo2#347]
barre d'outils d'une couleur distincte du panneau avec les options (meilleure distinction entre zone des outils et zone de listes, en particulier s'il n'y a pas d'icônes dans la liste)

![image](https://user-images.githubusercontent.com/32843565/67783769-1eea4a80-fa41-11e9-947a-627e869c58cc.png)

**Please tell us about your environment:**

* **Igo Version:**
1.0
* **Node:**

**Comment by mbarbeau** [comment]
Configurable:
color: white/grey/primary
