### ISSUE TITLE
recherche de couche trouve des groupes de couche

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#354]
La recherche trouve des groupes de couche se qui n'est pas idéale car l'utilisateur ne comprendra pas la différence et pourra ajouter le groupe à sa carte et le visuel ne sera vraiment pas bien.

Lors de l'ajout de ces groupes, il y a une seule couche d'ajoutée qui est une sandwich des couches contenues dans le groupe... Il ne faudrait pas que la recherche sorte les groupes.

Exemple:
recherche ecologie sort le groupe + les 8 couches contenue à l'intérieur du groupe.
![image](https://user-images.githubusercontent.com/32003632/68147178-7e47cf00-ff07-11e9-9060-c4129269c612.png)

Si on ajoute le groupe à la carte, ceci ajoute UNE seule couche qui concatène les 6 autres.
 
![image](https://user-images.githubusercontent.com/32003632/68147326-d1ba1d00-ff07-11e9-9219-ac5b3b870f4f.png)

chrome 77
* **Igo Version: 1.0**

**Comment by mbarbeau** [comment]
Ajout d'un setting 'type' pour choisir "couche". ou "groupe de couches".
Par défaut, seule couche est activée.
