### ISSUE TITLE
problème avec oeil  non grisé

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#356]
L'oeil qui affiche si la couche est visible ou non a une échelle fonctionne mal.

cas1: lors de l'ajout d'une couche avec une échelle d'affichage définie via la RECHERCHE, oeil n'est pas grisé même si la couche n'est pas visible à une échelle visible. 
![prob_oeil_pas_gris](https://user-images.githubusercontent.com/32003632/68246258-6e52ec80-ffe6-11e9-96de-b2255ad990be.gif)

cas2: Sur la couche de Zonage agricole (CPTAQ) l'oeil devrait être grisé un niveau de plus, il devient en couleur mais la couche ne s'affiche pas...
pour reproduire:  ajouter la couche agriculture/zonage agricole(CPTAQ) du catalogue donnée QC, zoomez jusqu'au niveau 10 = oeil n'est plus grisé et la couche n'est pas affichée = problème

* **Igo Version:**
1.0

**Comment by mbarbeau** [comment]
cas1: J'ai mis à jour le code en préprod, ça avait été corrigé
cas2: Erreur dans le mapfile, c'est corrigé en péprod
