### ISSUE TITLE
Filtre temporel: Années se réinitialisent même si le filtre est encore appliqué

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#359]
Lorsque l'on applique un filtre temporel, lorsque l'on reclique dessus pour retourner dans les paramètres, les dates de début et de fin se sont réinitialisées au lieu de demeurer celles du filtre qui lui demeure appliqué.

![image](https://user-images.githubusercontent.com/56965082/69344445-61b4d200-0c3d-11ea-9ed8-c017bb4a654c.png)

![image](https://user-images.githubusercontent.com/56965082/69344542-8446eb00-0c3d-11ea-9b58-6a0edd90e701.png)

**Comment by josee666** [comment]
Bug problématique car une fois réinitialisé ca devient en contradiction avec ce qui est affiché..
Sur la carte on affiche de 2000 à 2019 mais le filtre nous indique 1889 à 2019

**Comment by pelord** [comment]
@josee666 

Est-ce que tu peux m'envoyer la config de ton layer pour que je test?

**Comment by josee666** [comment]
{
        "id":"ca_feux",
        "title": "Feux de forêt ↺",
        "zIndex": 6,
        "visible": true,
        "metadata": {
            "extern": true
        },
        "sourceOptions": {
            "crossOrigin": "anonymous",
            "queryFormat": "htmlgml2",
            "queryHtmlTarget": "iframe",
            "url": "@host/ws/mffpecofor.fcgi",
            "params": {
                "layers": "ca_feux",
                "version": "1.3.0"
            },
            "type": "wms",
            "optionsFromCapabilities": true,
            "timeFilterable": true,
            "timeFilter": {
                "min": "1890",
                "max": "2019",
                "style": "calendar",
                "range": true,
                "step": 63072000000,
                "type": "year"
            }
        }
    },

**Comment by pelord** [comment]
Merci.
