### ISSUE TITLE
Liste des couches: Si une seule couche d'un contexte est bloquée (CSP) ou en erreur, aucune couche ne s'affiche

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#363]
Lorsqu'une couche est block CSP dans un context, aucune couche ne s'affiche dans le contexte.
La liste de couche est complètement vide 

Chrome 77.0

* **Igo Version:**
1.1 (.5)

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/587
