### ISSUE TITLE
scroll / swipe malfunction in mobile

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#374]
tablet ACER android 7.0
Chrome 79.0.3945

* **Igo Version:**
1.1.5 (foret ouverte production)

Swipe malfunction in some place in the app
1- in catalog at first level, the swipe work only if we are position on the arrow otherwise it doesn't work. Note that  in catalog in second level ( layer) it works bether (not right but bether...). (exemple in catalog DIF, in  group feux de foret annuel
2- in context list layer. work realy not well, maybe work 1/3
3- in the search result
Note in the context list and in html abort  it's fine all the time

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/commit/2d18eb2b1f5d070f4df684cad59bf29b4f532d73
https://github.com/infra-geo-ouverte/igo2/commit/3c3b23cb5461d520b4546a2108ea74f386157c92

**Comment by mbarbeau** [comment]
Problème connu de angular et mise en place du workaround suivant:
https://github.com/angular/components/issues/4892#issuecomment-307743989

Attention lors de la mise à jour vers angular 9.0: "GestureConfig is deprecated"
