### ISSUE TITLE
L'URL des apis défini dans proxy.conf.js n'est pas public

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#381]
https://github.com/infra-geo-ouverte/igo2-lib/blob/84348f150ef6807f8f15d14dbb26eb522296b1bd/proxy.conf.json#L13

**Comment by pelord** [comment]
@mbarbeau . Should we keep testgeoegl into the proxy?

**Comment by ameliebernier** [comment]
L'effet est que quand quelqu'un démarre le projet de l'assemblage sur son poste, la recherche et l'api pour la gestion des contextes ne sont pas utilisables

**Comment by pelord** [comment]
Que ce soit pour la lib OU l'assemblage.

**Comment by pelord** [comment]
il reste 

https://github.com/infra-geo-ouverte/igo2-lib/blob/c48eb10aa8aa75fc8cc8b0e5fbbac7bb6f3640fc/proxy.conf.json
