### ISSUE TITLE
Contextes: Sauvegarder un contexte sans utiliser l'api

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#388]
Pouvoir sauvegarder un contexte dans une instance IGO qui n'utilise pas l'api de contexte

**Comment by mbarbeau** [comment]
@drekss va travailler sur cet issue.

**Comment by ameliebernier** [comment]
Utiliser les outils d'importation et exportation pour sauvegarder des contextes et pourvoir les réimporter
