### ISSUE TITLE
Table des enregistrements: Montrer les enregistrements contenus dans la carte

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#390]
Pour les WFS et les WMS liés avec des services WFS, montrer les enregistrements contenus dans la carte dans le tableau en bas de la carte (expansion panel).

**Comment by pelord** [comment]
doublon de #445 ?

**Comment by ameliebernier** [comment]
Je comprenais que ça se faisait en deux étapes? Une dans la livraison 1.4 (afficher les enregistrements dans la table) et une plus tard pour les interactions plus avancées (afficher le contenu d'une sélection spatiale). Mais si c'est pas le cas on peut clarifier!

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/667
https://github.com/infra-geo-ouverte/igo2/pull/471
