### ISSUE TITLE
Croquis: Ajouter un outil de croquis/annotations sur la carte

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#391]
Outils pour ajouter des croquis et annotations à la carte.

Pourrait éventuellement être en lien avec d'autres outils : exportation, filtre spatial, etc.

**Comment by gignacnic** [comment]
@drekss va travailler sur cet issue.

**Comment by ameliebernier** [comment]
Ok super, ça serait bien de nous résumer ici ce que vous pensez faire! Quels outils, choix des symboles, intégration avec les autres outils (mesure, exportation, impression, ...)

**Comment by ameliebernier** [comment]
@gignacnic du travail a été commencé sur cet issue?

**Comment by gignacnic** [comment]
Oui, la fonctionnalité a été commencée par @drekss , mais elle n'est pas terminée encore.

![ezgif com-optimize](https://user-images.githubusercontent.com/5321940/93120019-bb84fd80-f690-11ea-9857-7a9b9a09adec.gif)
