### ISSUE TITLE
Liste des couches: Amélioration à l'ergonomie

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#397]
Il faudrait revoir l'ergonomie de l'outil "Carte" contenant la liste des couches.

-  Les outils applicables aux couches sont de plus en plus nombreux et l’espace dans l’interface limité. L'espace limité pour l’ouverture des outils à l’intérieur de la liste de couche est devenu problématique comme par exemple pour les filtres attributaires qui on besoin de plus d’espace.

- Un autre besoin étant de pouvoir avoir une vue de la liste de couche simplifié présentant toujours les légendes ouvertes. Simplement les couches actives visibles dans l'affichage de la carte avec leurs légendes.

- Un autre besoin exprimé est de pouvoir faire des actions sur plusieurs couches à la fois : déplacer, supprimer...

**Comment by ameliebernier** [comment]
Solution proposée : 

Il y aurait 2 onglets disponibles : **Couche** et **Légende**

- Couches : Sensiblement identique à la liste actuelle de couches, mais présente un nouveau comportement pour l'ouverture des outils des couches, un nouveau panneau dédié pour configurer les filtres d'une couche et une option pour appliquer des actions sur plusieurs couches à la fois; 

- Légende : une vue simplifié qui présente les couches visibles sur de la carte avec les légendes ouvertes.

Par défaut l’onglet "Couches" serait ouvert, mais une configuration serait possible
par contexte pour que ce soit "Légende" qui soit ouvert.

Si l'utilisateur quitte l'outil "Carte" pour d’autres outils génériques (recherche, catalogue, mesure, impression, partage, etc), au retour dans l'outil "Carte" le même onglet demeurerait sélectionné.

**Comment by ameliebernier** [comment]
Onglet **"Couches"** : 

-  Le bouton ![image](https://user-images.githubusercontent.com/45005853/75164013-24555a00-56ee-11ea-896a-4ede1885cc3b.png) ouvre un panneau en bas avec tous les outils disponibles pour la couche cliquée. Cela offre plus d'espace pour les outils et permet d'appliquer facilement une action sur plusieurs couches à la fois (voir le point suivant pour la sélection multiple).
![image](https://user-images.githubusercontent.com/45005853/75165578-9c248400-56f0-11ea-8003-042090126a0d.png)


- Un icône serait utilisé pour l’opacité/transparence ![image](https://user-images.githubusercontent.com/45005853/75164751-3e436c80-56ef-11ea-971d-890160fcf35a.png). L'icône prend beaucoup moins d’espace et représente mieux la modification de l’opacité/transparence. Sur clic le ‘slider’ sera ouvert au dessus du bouton (la présence du slider ne rendait pas évident que ce dernier s’appliquait sur l’opacité/transparence de la couche et prenait aussi beaucoup d’espace).

- Les boutons de filtres (attributaire ![image](https://user-images.githubusercontent.com/45005853/75165036-c0339580-56ef-11ea-9f80-6db7d8e7678d.png) ou temporel ![image](https://user-images.githubusercontent.com/45005853/75165084-d4779280-56ef-11ea-96cf-6b12a8a53e13.png), un nouveau panneau s'ouvre pour réaliser la configuration des filtres ouvrira et viendra couvrir la liste de couches.

    Exemple avec filtres attributaires:
![image](https://user-images.githubusercontent.com/45005853/75165332-3b954700-56f0-11ea-9657-92c4571d9f6d.png)

    Exemple avec filtre temporel : 
![image](https://user-images.githubusercontent.com/45005853/75165240-156fa700-56f0-11ea-8cfa-6832bb1b6c8b.png)

-  Remplacement du bouton en haut à droite (qui permettait ) pour un bouton permettant d'activer le mode sélection multiple de couches

**Comment by ameliebernier** [comment]
Onglet "Légende" :

- Présente une vue simplifié des couches visibles dans la carte, avec les légendes ouvertes : 
![image](https://user-images.githubusercontent.com/45005853/75172185-d98e0f00-56fa-11ea-8c76-e2802aa9412d.png)

- Si certaines couches ne sont pas visibles à l'échelle actuelle, en zoomant lorsque ces
dernières deviendront visibles dans la carte, elle s’ajouteront automatiquement.

**Comment by obegin3** [comment]
Cette solution a été présentée à notre équipe et nos pilotes de système supportant les usagers des applications spatiales du MTQ. 

Toutes les modifications ont été bien accueillies bien que nous aurions souhaité revoir le positionnement des filtres avancés. Par contre nous comprenons qu'une optimisation de l'espace peut être faite actuellement un positionnement horizontal dans l'espace alloué présentement.

Nous voyons d'un bon oeil ces modifications à l'interface.

**Comment by coulo3** [comment]
On a regardé rapidement les solutions proposées, et voici nos commentaires :
1-	L’idée de sortir les options de la couche dans une fenêtre est bonne pour faciliter le déplacement des couches, par contre, idéalement, nous pourrions évoluer vers le « drag and drop ».  L’icône de transparence est plus ou moins intuitif, mais rien de mieux à proposer.  S’assurer que le nom de couche soit le titre de la boîte. (comme présenté)
2-	Est-ce que le filtre temporel pourrait être conservé à même la boîte des options de la couche, plutôt que dans un panneau séparé? Pour le filtre attributaire, c’est ok puisque qu’il prend plus d’espace.
3-	Ok pour supprimer le bouton pour masquer les couches non visibles à l’échelle.
4-	Le nouveau bouton de sélection multiple ne nous semble pas très utile de notre côté. (à part pour la suppression des couches, autre option possible?)
5-	Onglet légende : Risque d’être mêlant pour l’utilisateur. Peu utile dans notre cas.

**Comment by pelord** [comment]
Le drag and drop est actuellement non possible du a une incompatibilité entre IGO2 et ANGULAR. À suivre dans les prochaines versions d'angular.

**Comment by ameliebernier** [comment]
@coulo3 quelques points de discussion : 
2 - Éventuellement il a déjà été discuté que les filtres attributaires et temporel pourraient être fusionnés dans la même section. D'une part, pour certains utilisateurs il n'y a pas vraiment de différence entre les deux concepts; d'autre part, les filtres temporels tels qu'ils ont été implémentés ne permettent pas d'être combinés avec les filtres attributaires (filtres OGC) et cela est dû au fait que ce n'est pas supporté par la norme WMS (si je ne me trompe pas). Donc idéalement, l'aspect temporel devrait être géré tel un filtre attributaire OGC, ce qui est de toute façon possible et qui permettrait de combiner les deux types de filtres.
4 - La sélection multiple permettrait les actions suivantes sur plusieurs couches à la fois : Changement d'ordre, suppression, opacité/transparence
5 - Pour nous le besoin était de voir la légende de plusieurs couches à la fois. Actuellement l'utilisateur doit afficher une à une les légendes des couches. On avait discuté d'un bouton pour tout afficher/masquer les légendes d'un coup, mais l'espace manquait pour ajouter un autre bouton (https://github.com/infra-geo-ouverte/igo2-lib/issues/507) et ce n'était pas souhaitable quand un grand nombre de couches est présent. Donc, l'onglet Légende tel que proposé s'avère utile pour nous quand l'utilisateur navigue dans la carte en mode "consultation", et qu'il veut simplement avoir la description de ce qui est visible pour lui dans la carte (par exemple, quand un contexte contient une multitude de couches mais que seulement certaines sont activées).

**Comment by ameliebernier** [comment]
Suggestion : 
Devrait-il y avoir un indicateur visuel si un filtre est actif sur une couche? Comme les filtres seront affichés dans une section à part, il ne sera pas possible pour l'utilisateur de savoir directement dans la liste des couches que des filtres sont actifs sur une couche. Cette information est toutefois très importante.

**Comment by ameliebernier** [comment]
Proposition de visuel pour L,indicateur de filtre actif sur une couche : 

![image](https://user-images.githubusercontent.com/45005853/76423312-f114fb00-637c-11ea-9a9f-983b9b6a62c0.png)

Dans la barre d'outil de la couche, peut-être mettre un petit badge rouge sur le bouton du filtre? Il pourrait aussi indiquer le nombre de filtres actifs : 

![image](https://user-images.githubusercontent.com/45005853/76423474-3fc29500-637d-11ea-823f-926063c23fe2.png)

**Comment by ameliebernier** [comment]
@coulo3 L'onglet "Légende" et l'outil de sélection multiple devraient être des options configurable, donc ils pourront être retirés de l'outil!

**Comment by obegin3** [comment]
Excellente idée le visuel pour le filtre.

**Comment by pelord** [comment]
P-être faire la même chose pour les données temporelle. 
@coulo3 , ca vous permettrais de retirer vos icones du titre de la donnée.

**Comment by ameliebernier** [comment]
@coulo3 J'ai créé un issue pour le changement d'ordre des couches par drag and drop, bien que ce ne soit pas possible pour l'instant ça reste une suggestion intéressante, à surveiller lorsque ce sera possible... https://github.com/infra-geo-ouverte/igo2/issues/419

**Comment by coulo3** [comment]
Parfait bonnes idées merci.
