### ISSUE TITLE
Contextes: Les filtres (temporel et attributaire) des couches ajoutées par le catalogue ne sont pas conservés dans le contexte

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#400]
When a layer from the catalog having a time or ogc filter is saved in a context, the attributes of the filter are not saved. When the context is later added to the map, there is no filter available for the layer.

**Comment by pelord** [comment]
@mbarbeau encore applicable?

**Comment by pelord** [comment]
@ameliebernier @mbarbeau  On ferme ceci? C'est lié a l'OptionsApi non?

**Comment by ameliebernier** [comment]
Je sais pas si c'est corrigé, mais me semble que IGO envoyait pas l'info à l'api justement...

**Comment by pelord** [comment]
@mbarbeau Encore valide?

**Comment by mbarbeau** [comment]
L'OptionsApi permet d'avoir les mêmes filtres dans le catalogue et dans le contexte.
Par contre, il n'est pas possible de modifier de sauvegarder un filtre différent, le filtre n'est pas passé à l'api. 
Je ferme, devrait-être un autre issue.
