### ISSUE TITLE
Impression: Pouvoir choisir la résolution

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#402]
La résolution actuelle n'est pas suffisante pour l'impression. Il faudrait permettre à l'utilisateur de choisir la résolution (faible, moyenne, grande?)

**Comment by pelord** [comment]
Des utilisateurs nous souligne aussi que ce serait intéressant de pouvoir se déplacer de manière réguli`re dans l'outil d'impression afin  de pouvoir imprimer 2ou plusieurs cartes adjacentes.

**Comment by LAMM26** [comment]
Semble être ok dans 16.0.0-rc.1. Seul élément, les attributions/échelle sont plutôt grosses à petite résolution.


![Image](https://github.com/infra-geo-ouverte/igo2/assets/83651899/802ef39e-3b1a-4af0-aa35-e912f18a5072)
