### ISSUE TITLE
Impression: Pouvoir imprimer en grand format à échelle fixe

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#403]
Il serait intéressant de pouvoir imprimer une carte grand format à une échelle donnée pour une zone qui dépasse l'étendue de la carte. Actuellement, la zone imprimée ne dépasse pas l'étendue de la carte. Pour les grands formats de carte (ex.: A0), ce n'est pas très intéressant car la carte pourrait couvrir une étendue beaucoup plus grande pour un niveau de zoom donné.

Proposition: Il pourrait y avoir deux mode d'impression (étendue de la carte (par défaut) - échelle fixe). En mode échelle fixe, selon le niveau de zoom et la résolution souhaitée, on pourrait afficher un graphique montrant l'étendue que la carte aurait et l'utilisateur pourrait déplacer ce cadre pour cibler l'étendue de sa carte.

**Comment by ameliebernier** [comment]
Il faut régler #402 avant

**Comment by pelord** [comment]
Il serait aussi intéressant d'ajouter a l'outil impression des fleches, pour imprimer la prochaine carte au nord, sud, est ou ouest. 

Donc on a un extent a l'entrée dans la carte, on imprime et on passe a la prochaine carte voisine.

**Comment by ameliebernier** [comment]
Cet issue a été réglé par le travail fait pour réaliser https://github.com/infra-geo-ouverte/igo2/issues/402.
