### ISSUE TITLE
Incapable de démarrer l'application en utilisant la branche master

### ISSUE THREAD

**Issue by geokarta** [infra-geo-ouverte/igo2#406]
**Please tell us about your environment:**

* **Igo Version:**
git clone de master

* **Node:** v12.12.0 

![image](https://user-images.githubusercontent.com/11087658/73948054-744ab900-48c6-11ea-8c96-654fb6750124.png)

**Comment by pelord** [comment]
Effectivement. La version MASTER est la version en développement, tandis que le package.json pointe sur la librairie (igo2-lib) stable (version 1.1.0). Donc OUI, c'est normal d'avoir ce bug.

TEMPORAIREMENT, fait
git checkout 1.1.0
npm install
npm start


À TRÈS COURT TERME:
Nous allons définir la branche MASTER comme étant la "stable" release et non pas comme la "dev". Donc au courant de la semaine prochaine, le problème ne sera plus la. DÉSOLÉ sincèrement.

**Comment by pelord** [comment]
@geokarta , test mon comment précédent, si le pb arrive de nouveau, c'est p-etre aussi la version de NODE qui cause problème. Reparle-moi en au besoin.

**Comment by pelord** [comment]
Essaye d'installer node 10.18.1
J’ai installé 12.14 et ça bug de mon côté aussi (pas le même message d’erreur).
Installe cette version et recommence la procédure d’installation
https://nodejs.org/dist/latest-v10.x/

**Comment by geokarta** [comment]
Malheureusement la solution #1 ne fonctionne pas:
![image](https://user-images.githubusercontent.com/11087658/73990096-21005700-4916-11ea-9efe-a82bb4f75577.png)

**Comment by geokarta** [comment]
Effectivement je pense que c'est la version de node.
J'ai tenté le tag 1.1.0 sans succès:
![image](https://user-images.githubusercontent.com/11087658/73990200-75a3d200-4916-11ea-9a05-2b7a37f2d3b8.png)

**Comment by geokarta** [comment]
Je confirme que la troisième solution est la bonne. J'ai un environnement fonctionnel.

Merci!

**Comment by pelord** [comment]
J'ajouterai au readme les version testés et fonctionnelles de node.

**Comment by pelord** [comment]
C'est dans un pull request:

https://github.com/infra-geo-ouverte/igo2/pull/404/commits/92cef323cca5dedb4de52c3da2845ddfcc8a7181
