### ISSUE TITLE
Erreur pour "Ouvrir le lien externe" lorsque c'est une municipalité

### ISSUE THREAD

**Issue by mikesmichael** [infra-geo-ouverte/igo2#409]
Lorsque l'on recherche une municipalité, on obtient une erreur lorsque l'on clique sur "Ouvrir le lien externe" de GoogleMaps.

Test fait avec: les municipalités:
"Gouvernement régional d'Eeyou Istchee Baie-James" => `about:blank#blocked`
et 
"Maskinongé" => `413. That’s an error. Your client issued a request that was too large. That’s all we know.`

**Comment by PhilippeLafreniere18** [comment]
Même si le reste des entités ne donnent pas nécessairement d'erreurs, beaucoup n'aboutissent à rien dans google maps en raison de la géométrie complexe (pleins de points lon/lat). Définitivement à travailler

**Comment by mbarbeau** [comment]
On a 2 choix possibles
1) Passer le centroide de la géométrie = Précision assurée par contre seulement une pin au milieu et n'est pas associé à un élément dans google.
2) Passer le nom de l'entité = Est associé à un élément dans google mais peut, dans certains cas, nous apporter à un mauvais endroit (noms identiques)

Vote !
Si vous préférez 1, mettez un coeur en réaction
Si vous préférez 2, mettez une fusée en réaction

**Comment by ameliebernier** [comment]
Pour moi ça serait l'option 2, le but de l'ouvrir dans Google c'est quand même qu'il soit lié à l'élément de google... comme si tu avais fait la recherche dans Google

**Comment by mbarbeau** [comment]
Complément d'informations:
Pour les points, on passe les coordonnées. Donc faudrait être cohérent et passer les points avec des noms au lieu de la coordonnée.

**Comment by mbarbeau** [comment]
Comme sous-question: 
Le but de l'ouvrir dans Google est d'avoir l'élément de Google lié ou de l'ouvrir à la bonne place.

**Comment by PhilippeLafreniere18** [comment]
> Comme sous-question:
> Le but de l'ouvrir dans Google est d'avoir l'élément de Google lié ou de l'ouvrir à la bonne place ?

Je pense que d'ouvrir Google en plein milieu d'une rue qui se trouve au centroïde d'une municipalité par exemple, ne dit pas grand chose... De plus, Google fait aussi une association avec l'adresse la plus proche quand tu lui passes une coordonnée

**Comment by mikesmichael** [comment]
Je pense que je dirais choix 1 aussi. Étant donné que tu recherches à te localiser dans google map je pense que c'est ce qui est le plus important c'est de localiser la position plutôt que l'information. Une fois que tu es localisé, tu pourras poursuivre tes recherches pour obtenir les informations google si tu le désires. Si tu prends l'option 2, tu ne seras pas capable de te retrouver pour poursuivre les recherches.  Par exemple si tu cherches une borne sumi dans igo et tu veux la retrouver dans google, l'option 2 va te faire chier car tu ne les retrouveras jamais à partir de ses informations.

**Comment by ameliebernier** [comment]
Bon je suis d,accord avec les deux commentaires précédents, en fait le meilleur comportement dépend du type d'élément... pour une mun effectivement, ça ne fait pas de sens d'être localisé à une adresse au centre de celle-ci. Pour une borne par contre, oui on voudrait être sur le point

**Comment by mbarbeau** [comment]
Ça complique les affaires si ce n'est pas général:
si borne sumi -> coordonnées
si municipalité -> utiliser designation + nom + regadmin
si route -> utiliser nom + mun 
si adresse -> utiliser nom + mun + code postale
si lieu -> ?
si ... -> ....

**Comment by mikesmichael** [comment]
Faire les 2 options dans le menu, genre: 
recherche maps avec localisation
recherche maps avec détails

Bonne idée?

**Comment by ameliebernier** [comment]
Pour l'adresse, je ne pense pas que ça serait un problème d'utiliser la coordonnée...

Mais sinon on retire le lien Google Maps quand ça fait pas de sens? Car pour une municipalité, ça ne fait pas de sens de localiser un point, ce n'est pas utile.

**Comment by PhilippeLafreniere18** [comment]
On peut garder la coordonnée pour les points et faire un custom pour les lignes et les polygones avec nom ou simplement l'enlever pour les lignes et polygones... Si on veut garder ça générique

**Comment by mikesmichael** [comment]
Je pense que de laisser le choix à l'utilisateur de chercher soit la description ou la localisation ça reste le plus simple (à faire, à utiliser, à configurer) et ça laisse la flexibilité de pouvoir faire les 2 recherches selon ce que l'utilisateur à envie de faire. Si on commence à paramétrer pour chacun des types de recherche c'est sur que ça va arriver qu'un utilisateur va vouloir la localisation pour une recherche X et qu'un autre voudra la description.

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/682
