### ISSUE TITLE
Importation: Sauvegarder les couches importées dans un contexte

### ISSUE THREAD

**Issue by mbarbeau** [infra-geo-ouverte/igo2#418]

**Comment by pelord** [comment]
@mbarbeau  C'est l'outil d'export du contexte?

**Comment by pelord** [comment]
@mbarbeau  Toujours d'actualité?

**Comment by mbarbeau** [comment]
Un peu flou la raison de cet issue. Si ça se rapporte à l'outil d'import/export, c'est maintenant possible.
