### ISSUE TITLE
GetInfo Panel zoomtofeature avec cell paysage fait perdrela carte

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#420]
Lorsqu'on fait un Getinfo sur un cellulaire en mode paysage (sur le côté) et que l'on clique sur le bouton zoom to feature du toaster, il perd la carte.

version igo : 1.2 
Sur : https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/?context=qc911
Zoom sur la position GPS et clique sur la carte et zoom to feature.

**Comment by pelord** [comment]
@gignacnic Est-ce encore vrai?

**Comment by pelord** [comment]
résolu dans la version 1.10
