### ISSUE TITLE
Utilitaires: Ajouté lien Google Earth Timelapse sur click droit et/ou coordonné

### ISSUE THREAD

**Issue by hugbe8** [infra-geo-ouverte/igo2#421]
* **Igo Version:** 1.2.0
Si personnnes n'a de commentaire et n'y voit d'objection, je l'intégrerais d'ici 1-2 semaines.

![image](https://user-images.githubusercontent.com/1155637/76524733-f0de3380-6440-11ea-8812-ca78f44ecff4.png)

**Comment by ameliebernier** [comment]
Intéressant, est-ce que la géométrie pourra être affichée pour faciliter la localisation? De ce que je comprends aussi, on ne peut pas zoomer très proche donc l'utilisateur pourrait perdre un peu le contexte de sa localisation

**Comment by hugbe8** [comment]
Effectivement, je viens de me rendre compte que la résolution des images ne permet pas de s'approcher pour une consultation à grande échelle. Dans ces condition, je crois que ça n'apporte pas grand chose à l'utilisateur et je penses laisser tomber ma proposition.
