### ISSUE TITLE
Amélioration du rendu de l'échelle graphique

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#430]
L'échelle graphique est peu visible sur fond foncé. (Exemple: photos aériennes)
Ajouter un halo.

**Comment by mbarbeau** [comment]
![image](https://user-images.githubusercontent.com/2047019/78037495-a4985c00-7339-11ea-96b1-2a994eab4bf9.png)

**Comment by coulo3** [comment]
Exactement :)

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/commit/8cb8b02bb4f2292846553079cf894168f24ef422
