### ISSUE TITLE
GetInfo: Pouvoir redimensionner/déplacer la fenêtre

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#431]
**Please tell us about your environment:**

* **Igo Version:**

* **Node:**

**Comment by ameliebernier** [comment]
Nous avons un besoin semblable (agrandir la fenêtre du getInfo pour les données qui ont beaucoup d'attributs)

Deux solutions ont été proposées (mais aucune n'a fait l'unanimité!), soit de : 
1 - Pouvoir "docker" la fenêtre du GetInfo dans la section de gauche (peut-être comme un outil?) 
2 - Pouvoir agrandir la fenêtre pour qu'elle occupe plus d'espace par-dessus la carte

Avez-vous des propositions de ce qui pourrait être fait?

**Comment by coulo3** [comment]
Est-ce que ce serait possible que la fenêtre devienne complètement indépendante lorsqu'on la sort de son emplacement initial? Exemple si on a 2 écrans pouvoir la draguer sur le 2e écran?

**Comment by ameliebernier** [comment]
@mbarbeau @pelord c'est possible? Avez-vous des propositions?

**Comment by mbarbeau** [comment]
Ça nécessite d'ouvrir une connexion entre 2 fenêtres.
Le plus simple serait d'avoir une option dans le menu (+ raccourci) pour agrandir la fenêtre en utilisant l'espace de la carte.

**Comment by ameliebernier** [comment]
C'est juste dommage de masquer la carte. En même temps, ça peut être utile pour le mobile

**Comment by mikesmichael** [comment]
Sinon une icône dans le coin du getInfo qui permet de "détacher" la fenêtre en l'ouvrant comme une fenêtre distinctive. Après ça l'utilisateur peut faire ce qu'il veut avec la fenêtre, le lien est perdu. S'il fait d'autres getInfo, ça ouvre le getInfo classique sur la carte et il a toujours l'option pour "détacher" le getInfo avec le même bouton. L'utilisateur peut ainsi se retrouver avec plein de fenêtre détachée de getInfo qu'il gérera lui-même.

**Comment by coulo3** [comment]
Intéressant comme solution! La fenêtre détachée pourrait s'agrandir?

**Comment by mikesmichael** [comment]
Oui ça serait possible la fenêtre serait une fenêtre navigateur à part. reste à voir ce que  l'équipe igo pense de cette proposition.

**Comment by ameliebernier** [comment]
L'issue sera séparé en deux phase : 
1 - Réduire/agrandir la fenêtre avec un bouton (voir issue #442 )
2 - Pouvoir repositionner la fenêtre du getInfo

**Comment by ameliebernier** [comment]
La redimension de la fenêtre ne fonctionne pas correctement avec un contenu HTML

**Comment by josee666** [comment]
Le merge associé ici concerne l'agrandissement et la disposition en mode HTML. Si le besoin de détacher la fenetre est toujorus présent. Reouvrir une autre demande. Merci
