### ISSUE TITLE
Possibilité de traduire les toasts (messages) en anglais

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#433]

**Comment by coulo3** [comment]
Lorsque Google est paramétré en anglais, nous aimerions pouvoir traduire les messages explicatifs qui apparaissent lors de la sélection d'un contexte (encadré vert en bas à droite dans Forêt ouverte)

**Comment by mbarbeau** [comment]
Je crois que c'est déjà possible en mettant une clé de traduction au lieu du texte et mettre les messages dans les locales.

**Comment by josee666** [comment]
La cle de traduction fonctionne uniquement sur le paramètre text du message et ne fonctionne pas sur le param html. Par contre on peut insérer du html dans le param text qui est bien rendu. La seule différence est que le paramètre text présente un icone, ce qui n'est pas présent en html. 
Exemple de la différence avec param text dans le message plutot que html:
![image](https://user-images.githubusercontent.com/32003632/86359703-58fa9480-bc3f-11ea-9cb6-ba4bddcb1e82.png)
![image](https://user-images.githubusercontent.com/32003632/86359741-6748b080-bc3f-11ea-8f4d-e857b3aca760.png)

@coulo3 Est-ce qu'il est correct pour vous d'affichez vos message avec l'icone? De cette facon les traductions fonctionneront.

**Comment by PhilippeLafreniere18** [comment]
Effectivement, les traductions fonctionnent de cette façon. Nous trouverons simplement une manière de gérer plus facilement la présence de l'icône de notification.

**Comment by coulo3** [comment]
Approuvé :)
