### ISSUE TITLE
Ajuster le délai pour ne pas voir apparaître ce message au chargement des contextes 

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#438]
![image](https://user-images.githubusercontent.com/56965082/79759263-74b2f780-82ec-11ea-8131-3fd609025657.png)

**Comment by pelord** [comment]
Le correctif serait apporté dans la prochaine version.

https://github.com/infra-geo-ouverte/igo2-lib/pull/625/commits/fbd2a221213e8f634368f7fa64b040ae6d06832b
