### ISSUE TITLE
Ajouter une barre d'outils dans le menu des contextes comme l'outil de la carte

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#440]
- Filtrer les contextes (Fait)
- Tri par ordre alphabétique
- Choisir le profil (911, SC...)
- Ajouter un contexte

**Comment by mbarbeau** [comment]
Création d'un nouveau ticket pour le point manquant:
- Choisir le profil (911, SC...) 

https://github.com/infra-geo-ouverte/igo2/issues/447
