### ISSUE TITLE
Catalogue: Regrouper les catalogues par catégorie (ergonomie)

### ISSUE THREAD

**Issue by hugbe8** [infra-geo-ouverte/igo2#441]
Issue: When there is a lot of catalog, users have a hard time finding their way around.

Proposal: May be could group them by themes at the first level of the catalog tool. Grouping could be done by configuration.

![image](https://user-images.githubusercontent.com/1155637/76240563-dbcb8f80-6209-11ea-951a-5d456582c7c2.png)

**Igo Version:** 1.2.0

similar issue: infra-geo-ouverte/igo2-lib#600

**Comment by pelord** [comment]
Je ne pense pas que l'exemple fourni sera réalisé.. mais je vais envisager cette logique, du moins pour les partenaires externes...
À suivre
