### ISSUE TITLE
GetInfo: Pouvoir agrandir/réduire la taille de la fenêtre

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#442]
Certains utilisateurs veulent pouvoir agrandit la fenêtre du getInfo pour permettre de consulter plus facilement l'ensemble des attributs.

Un bouton permettrait d'agrandir la fenêtre our qu'elle occupe plus d'espace en hauteur (au-dessus de la carte) ou la réduire pour quelle revienne à sa taille initiale.

Idéalement le choix de l'utilisateur serait conservé dans ses préférences #443.

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2/pull/466
