### ISSUE TITLE
Préférences: Ajout d'un concept de préférences utilisateur (authentifié ou non)

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#443]
Ajouter la notion de préférences utilisateur qui persistent lorsque l'utilisateur revient dans l'application, en mode authentifié ou non.

Pourrait être utilisé dans un premier temps pour le choix de dimension de la fenêtre du getInfo #442 (si l'utilisateur a agrandi la fenêtre, elle resterait dans le même état lors d'une prochaine connexion).

**Comment by mbarbeau** [comment]
Fait dans 1.4
