### ISSUE TITLE
Afficher une table attributaire provenant d'un WMS/WFS suite à une sélection polygonale

### ISSUE THREAD

**Issue by obegin3** [infra-geo-ouverte/igo2#445]
Dans IGO2, permettre la sélection polygonale d'une couche et l'affichage résultant dans une table attributaire (input: combinaison d'une couche WMS/WFS)

**Comment by ameliebernier** [comment]
Est-ce qu'il y a un lien à faire avec l'outil de filtre spatial? Le résultat de la sélection par le filtre spatial pourrait s'afficher dans la même table. @PhilippeLafreniere18

**Comment by mbarbeau** [comment]
En lien aveec https://github.com/infra-geo-ouverte/igo2/issues/390

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/667
https://github.com/infra-geo-ouverte/igo2/pull/471
