### ISSUE TITLE
Permettre l'exportation en fichier compatible excel

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#452]
L'exportation en fichier Excel serait d'une utilité pour ceux dont les résultats souhaités doivent être déjà formaté pour être ouvert en tableau Excel. 

Présentement, le format CSV doit être reformaté à partir des séparateurs pour apparaître correctement sur Excel.

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/668
