### ISSUE TITLE
Gestion des couches : Changer la symbologie d'une couche vectorielle

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#454]
Permettre à l'utilisateur de changer la couleur sur une couche vectorielle

**Comment by ameliebernier** [comment]
@matrottier

**Comment by ameliebernier** [comment]
Utiliser les mêmes contrôles que l'outil de dessin?

**Comment by pelord** [comment]
fermé. sera traité dans https://github.com/infra-geo-ouverte/igo2/issues/785
