### ISSUE TITLE
Rideau (layer swipe) pour balayer l'affichage entre 2 photos de 2 dates différentes

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#458]
Avoir un rideau vertical pour balayer l'affichage entre deux photos de deux dates différentes (ou deux fonds de carte, exemple routier et imagerie).

Est-ce que ça pourrait être lié au filtre temporel?

Exemple : https://openlayers.org/en/latest/examples/layer-swipe.html

**Comment by pelord** [comment]
Sera dans la prochaine version.
