### ISSUE TITLE
Gestion des couches : Masquer/Afficher toutes les couches à la fois

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#464]
Avoir une fonction permettant d’allumer et d’éteindre toutes les couches à la fois

**Comment by mbarbeau** [comment]
Possible avec la 1.3

**Comment by mbarbeau** [comment]
Pareil que:
https://github.com/infra-geo-ouverte/igo2/issues/453

**Comment by ameliebernier** [comment]
Oui et non, dépendamment de si on veut que ça fonctionne avec la sélection ou que ce soit pour toutes les couches
