### ISSUE TITLE
Gestion des couches : Appliquer le changement de transparence en direct sur la couche

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#465]
Lorsque l’on glisse le curseur d’opacité, le changement sur la carte devrait se faire automatiquement, ce qui permet d'ajuster plus facilement la transparence au niveau souhaité.

**Comment by josee666** [comment]
complément d'info: À l'heure actuelle la transparence s'applique lorsqu'on relache le bouton.

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/802

**Comment by pelord** [comment]
Sera fait dans la version 1.6.
