### ISSUE TITLE
Indicateur de filtre temporel s'active même si aucun filtre appliqué

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#467]
Quand on entre dans l'onglet filtre, si on ne modifie pas les années par défaut, l'indicateur s'active comme quoi un filtre est appliqué lorsqu'on le ferme. Créer un bouton reset?

[467.zip](https://github.com/infra-geo-ouverte/igo2/files/4713022/467.zip)

**Comment by pelord** [comment]
P-être le lien public hors chat si possible !

**Comment by coulo3** [comment]
[467.zip](https://github.com/infra-geo-ouverte/igo2/files/4713017/467.zip)

**Comment by coulo3** [comment]
> P-être mettre le lien public hors chat si possible !

En effet!
