### ISSUE TITLE
Recherche - Le résultat précédent n'est pas supprimé de la carte lors d'une nouvelle recherche

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#473]
* **Igo Version:**
1.3.1

Recherche - Le résultat précédent n'est pas supprimé de la carte lors d'une nouvelle recherche.
Ainsi, plusieurs géométries sont conservées à la carte lors des recherches subséquentes.

https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/

![NwlA2qe3QL](https://user-images.githubusercontent.com/7397743/85055221-378fa800-b16b-11ea-8532-b7bf6814828c.gif)

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/681
