### ISSUE TITLE
Ajuster l'ordre des années dans les résultats de recherche en décroissant

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#474]
![ordre](https://user-images.githubusercontent.com/56965082/85169863-89ebca00-b23a-11ea-998c-0819adad714c.png)

**Comment by coulo3** [comment]
Si possible maintenir le nom des couches en ordre alphabétique, mais lorsqu'une année différencie le nom des couches, les trier en ordre décroissant.

**Comment by mbarbeau** [comment]
Oui c'est un peu complexe par contre la demande !
Pour l'instant, le tri est par score avec l'élément recherché, on peut ajouter un tri ensuite par ordre alphabétique si le score est identique. Par contre ajouter un tri avec une année qui est située à la fin du champs me semble difficile à mettre en place. Faudrait mettre un champs différent utilisé pour le tri et piloter ça. À voir si ça vaut vraiment la peine !

**Comment by pelord** [comment]
@mbarbeau  Est-ce que l'on ferme puisque c'est lié a l'api de recherche de layers... non pas a igo.

**Comment by coulo3** [comment]
Trop complexe pour le gain.
