### ISSUE TITLE
Directions : Routing by link method doesn't always appear 

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#477]

**Comment by PhilippeLafreniere18** [comment]
Seems to be depending on if you are authenticated or not... but sometimes directions tool need to be triggered to see the route

**Comment by pelord** [comment]
@PhilippeLafreniere18  Is it fixed?

**Comment by PhilippeLafreniere18** [comment]
@pelord  Not really, it is always inconsistent..

**Comment by pelord** [comment]
Fixed 1.10 +
