### ISSUE TITLE
Pouvoir ajouter des catalogues/couches ESRI REST

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#482]
Les options de configuration actuelles ne permettent pas d'ajouter des catalogues ESRI REST ou des couches de ces services dans les catalogues composites.

Bien que le datasource existe dans la librairie, ce format ne peut pas être utilisé par simple configuration.

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/709
