### ISSUE TITLE
Inverser les couleurs du bouton de menu pour qu'il soit plus visible.

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#486]
Nous avons des commentaires à l'effet que des utilisateurs ne remarquent pas le bouton de menu et ont donc de la difficulté à démarrer leur navigation.  Inverser les couleurs de façon à ce que le bouton soit vert avec des lignes blanches pourrait aider à mieux le voir.

**Comment by ameliebernier** [comment]
Le problème avec l'inversion des couleurs du bouton, c'est que quand le menu est ouvert, je ne sais pas si ça serait harmonieux visuellement avec la barre de titre et la barre d'outils qui sont déjà de la même couleur.

- Est-ce que le bouton pourrait redevenir blanc quand le menu est ouvert?
- Ou est-ce qu'on pourrait mettre le menu ouvert par défaut en mode "desktop"?

**Comment by majme1** [comment]
La suggestion vient des tests utilisateurs effectués pour la carte géo-innondations
![image](https://user-images.githubusercontent.com/57358502/93807855-3b731080-fc19-11ea-9c74-f8276b95d563.png)

**Comment by majme1** [comment]
Mais effectivement, le bouton va se fondre avec les autres onglets du menu principal une fois ouvert s'il est de la même couleur.

**Comment by ameliebernier** [comment]
Autre chose qui serait intéressante : Il est déjà possible aussi par paramètre d'URL d'ouvrir IGO avec un outil spécifique déjà ouvert. Donc on pourrait aller plus loin, soit rendre configurable quel outil est visible à l'ouverture de l'application.

Comme cela il serait possible par exemple que l'application s'ouvre avec le menu des contextes visible.

**Comment by pelord** [comment]
@josee666 On le ferme?
