### ISSUE TITLE
Aviser l'utilisateur qu'un nombre de couches élevé peut affecter la performance

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#493]
Tel que mentionné suite à la réalisation de https://github.com/infra-geo-ouverte/igo2/issues/453, avoir un trop grand nombre de couches visibles sur la carte affecte grandement la performance de la navigation sur la carte

Exemple : https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/?context=inondation&zoom=14&center=-71.1866,46.90184&visiblelayers=*&invisiblelayers=bb12b9975bbb86d5f5ca36ac4958c6be,e5a953873cdd7abd17e0d8d90c763232,430988e95780b3ea5d7ea2c49173ee91,fond_osm&wmsUrl=/ws/mffpecofor.fcgi,/apis/wss/transport.fcgi&layers=(iqs_pot_epn:igoz52,iqs_pot_epb:igoz51,iqs_pot_epr:igoz50,iqs_pot_sab:igoz49,iqs_pot_pib:igoz48,iqs_pot_pig:igoz47,iqs_pot_bop:igoz46,iqs_pot_pex:igoz45,iqs_pot_tho:igoz44,accr_st_ers:igoz43,accr_st_boj:igoz42,accr_st_err:igoz41),(convi_velo_glv:igoz40,DQ_CYCLABLE_MUN_L:igoz39,AQ_CHEMIN_FOR:igoz38,AQ_CHEMIN_FOR_SEC:igoz37,etablissement_mtq:igoz36,bgr_v_dirct_genrl_geomt_act:igoz35,bgr_v_dirct_terrt_geomt_act:igoz34,evenements:igoz33,circulation_routier:igoz32,parc_routier:igoz31,investissements:igoz30,pes_v_limtn_charg:igoz29,radars_photos:igoz28,aq_camion:igoz27,sortie_aut:igoz26,gsq_v_desc_strct_tri:igoz25,bgr_v_sous_route_res_sup_act:igoz24,telephone_urg:igoz23,villagerelais:igoz22,zones_degel:igoz21)

Devrait-on afficher un avertissement à l'utilisateur à partir d'un certain nombre de couches? Même désactiver certaines fonctionnalités quand il y a trop de couches dur la carte?

Il faudrait évaluer dans un premier temps à partir de combien de couches la situation devient problématique.

**Comment by ameliebernier** [comment]
Finalement est-ce que https://github.com/infra-geo-ouverte/igo2/issues/453 cause problème? Cet issue est toujours pertinent? @pelord @josee666 @mbarbeau

**Comment by pelord** [comment]
Je n'ai pas eu d'écho des usagers. On pourrait fermer et réouvrir au besoin.

**Comment by pelord** [comment]
@infra-geo-ouverte/depot-central-igo

Vous pensez quoi de ce correctif.
infra-geo-ouverte/igo2-lib@5b7ebc5

Il permet d'appeler seulement l'extent de la map plutot que 1.5x sa taille. Sa semble régler le problème.
Avec le correctif :
https://geoegl.msp.gouv.qc.ca/igo2/mtq-quebec/?visiblelayers=*
Sans le correctif
https://geoegl.msp.gouv.qc.ca/igo2/apercu-qc/?context=mtq&visiblelayers=*

Vous devez faire le test sur un écran de grande taille + 1700px de largeur
