### ISSUE TITLE
Configuration du navigateur par un JSON

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#5]
Permettre la configuration pour chaque contexte et utilisateurs à partir d'un fichier JSON qui va supporter l'ajout de fond de carte, couche WMS, couche WFS, outil/service, déclencheur, style, type d'authentification, etc.

**Comment by gignacnic** [comment]
Le JSON comme fichier de configuration du navigateur est fonctionnel. Par contre, il ne permet que de mettre une couche WMS et d'ajouter un outil dans le navigateur, il faudrait donc ajouter ces éléments pouvant être mis dans la config:
1- Couches WMS par le getcapabilities (protocol:getcapabilities)
2- Fond de carte WMTS ou TMS (protocol:tms et protocol:wmts)
3- Couche vecteur (protolcol:json protocol:wfs)
4- Groupe de couche (group-layer, group-name, )
5- Paramètres d'une couche en particulier (scalemin, scalemax, metadataURL, active, visible, opacity)
6- Contexte de la carte (zoom, center, zoomlevel, maxresolution, projection)

**Comment by matrottier** [comment]
à séparer en plusieurs "issues"
