### ISSUE TITLE
Filtres : Simplifier l'interface des filtres ogc (incluant l'aspect temporel)

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#503]
Pousser plus loin la configuration des filtres attributaires simplifées et des filtres temporels une fois que ceux-ci seront unifiés. Il serait intéressant par exemple, d'avoir des cases à cocher pour les filtres attributaires (par catégorie) au lieu des boutons, et pouvoir prédéfinir des filtres temporels (ex.: calendrier ou slider pour certains champs)

**Comment by ameliebernier** [comment]
Voici le genre d'interface auquel on pensait pour simplifier l'utilisation des filtres par l'utilisateur. Il manquerait quelque chose pour la valeurs numériques. 
![image](https://user-images.githubusercontent.com/45005853/97626282-fa340480-19ff-11eb-83f9-6f639f9122e1.png)

**Comment by pelord** [comment]
Est-ce que vous voulez inclure les animations temporelle ?

**Comment by ameliebernier** [comment]
À mon sens une animation temporelle ce n,est pas vraiment un filtre... je ne le verrais pas dans cette section

**Comment by pelord** [comment]
Ok. Et c'est une bonne proposition. Sachez que nous allons bientôt travailler sur un service de domaine de valeur, sous format code, valeur.
