### ISSUE TITLE
Aide à l'utilisateur : Bonifier le contenu du tour interactif général

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#504]
Suite à la première version du guide rendue disponible, le contenu serait à bonifier pour le rendre un peu plus détaillé et idéalement applicable à n'importe quelle instance?

**Comment by PhilippeLafreniere18** [comment]
Pour la version 1.6, on ajoute les tours pour l'outil de contexte et l'outil de carte.

**Comment by ameliebernier** [comment]
Je vais fermer cet issue, on pourra en faire des spécifiques pour les outils qui manquent @PhilippeLafreniere18
