### ISSUE TITLE
Ajout d'une couche par le catalogue, le + fonctionne de façon intermittente.

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#508]
Parfois en cliquant sur le + la couche ne s'ajoute pas.  Il faut cliquer 2 fois.

**Comment by ameliebernier** [comment]
Moi aussi ça arrive souvent, on dirait que ce ne sont pas toutes les parties du bouton qui sont fonctionnelles, ou je sais pas s'il y a parfois un glitch avec le survol qui fait afficher un apercu des données sur la carte...

**Comment by pelord** [comment]
l'apercu c'est voulu... le but est justement
sur survol du bouton= apercu
lorsque l'ont quitte le bouton = supression de l,apercu
clic = ajout de la couche.

**Comment by ameliebernier** [comment]
Oui mais quand on clique, ça ne fonctionne pas tout le temps

**Comment by pelord** [comment]
J'ai essayé de faire un correctif.
Vraiment difficile a reproduire. En espérant que ca fait la job
https://github.com/infra-geo-ouverte/igo2-lib/pull/667/commits/167167ce25d7c6658d2980943b5e6df15c1425fb

**Comment by ameliebernier** [comment]
Oui en effet, j'ai essayé de faire un vidéo pour le montrer, mais comme on voyait pas vraiment quand je cliquais ça n'aidait pas tant

**Comment by pelord** [comment]
J'ai essayé 10 -15 min de reproduire le bug.. sans trop réussir.. et les rares fois que ca marchais, je ne comprennais pas comment j'avais déclanché le bug.

**Comment by coulo3** [comment]
Est-ce que la correction est en préprod?

**Comment by pelord** [comment]
non. dans la prochaine version (1.5) d'igo2-lib

**Comment by pelord** [comment]
@coulo3 Est-ce réglé?

**Comment by coulo3** [comment]
J'ai réussi a le reproduire mais après plusieurs essais.  Par contre si tout le monde est d'accord je laisserais ça comme ça, étant donné que c'est très mineur.

**Comment by coulo3** [comment]
C'est beau de même
