### ISSUE TITLE
Fixer les options dans le haut dans Ma carte

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#509]
![image](https://user-images.githubusercontent.com/56965082/93509604-f041c080-f8ed-11ea-89d9-3fb62efec630.png)

**Comment by majme1** [comment]
![Filtres](https://user-images.githubusercontent.com/57358502/93807551-c99ac700-fc18-11ea-912b-8fbdbabfe72f.gif)
