### ISSUE TITLE
Pouvoir agrandir/réduire la fenêtre du getinfo directement dans la barre de la fenêtre

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#511]
Le bouton n'est pas évident à trouver, aussi on peut vouloir agrandit et réduire la fenêtre plusieurs fois pendant la consultation des données

**Comment by coulo3** [comment]
L'agrandissement de la fenêtre n'est pas suffisant du côté de Forêt ouverte.  Elle s'agrandit très peu, difficile de consulter.

**Comment by ameliebernier** [comment]
Il y a une problématique dans l'instance, il faudrait voir à la régler... c'est peut être en lien avec le contenu html? Car pour nous effectivement elle s'agrandit pas mal plus que ça.

**Comment by ameliebernier** [comment]
Il faudrait ouvrir un issue différent pour cela
