### ISSUE TITLE
Couches WMS : Afficher le contenu du tag "abstract" si "metadata_url" est absent

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#514]
Actuellement, la présence de la balise metadata_url dans la définition d'une couche WMS ajoute un bouton (i) dans le catalogue, les résultats de recherche et l'onglet Carte qui permet d'ouvrir la page en question.

Cependant pour certaines couches WMS externes que nous intégrons, nous avons seulement des renseignements dans la balise "abstract". 

Ça serait intéressant que quand metadata_url n'est pas défini, mais qu'il y a du contenu dans "abstract", on affiche le bouton (i) avec une interaction qui permettrait de voir le contenu de la balise "abstract" (ex.: dans une fenêtre en cliquant sur le (i))

**Comment by pelord** [comment]
C'est déja possible de le faire. Donne moi quelques minutes, je te fourni l,exemple.

**Comment by pelord** [comment]
https://infra-geo-ouverte.github.io/igo2-lib/#/catalog
voir le catalogue "Controling tooltip format"

**Comment by ameliebernier** [comment]
Ah ben là! Je regarde ça merci

**Comment by pelord** [comment]
J'ai pas testé, mais c'étais ca le but.

**Comment by ameliebernier** [comment]
Ok la config actuelle permet d'afficher le contenu de "Abstract" dans un tooltip sur le nom de la couche dans l'onglet carte, cette demande serait pour l'intégrer avec le bouton (i) des métadonnées (donc en partie couvert, mais à bonifier)

**Comment by pelord** [comment]
Via la config d'un catalogue ![image](https://user-images.githubusercontent.com/7397743/93636932-c0b0b800-f9c2-11ea-83f3-f7508c6fea62.png)


ou d'un layer
![image](https://user-images.githubusercontent.com/7397743/93636988-d8883c00-f9c2-11ea-8aa6-373efb8dfcfa.png)

**Comment by pelord** [comment]
Correctif partiel:
https://github.com/infra-geo-ouverte/igo2-lib/pull/725

**Comment by mbarbeau** [comment]
Ajouter la source et autres infos intéressantes

**Comment by mbarbeau** [comment]
doit être une option:
- tjrs vers metadata url directement
- ou tjrs montrer l'abstract avant le lien vers la fiche

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/799
