### ISSUE TITLE
Catalogue composite : Pouvoir spécifier le nom d'une couche (alias)

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#515]
Quand on configure un catalogue composite et qu'on intègre des couches d'un WMS dans un groupe, ce serait intéressant de pouvoir "overrider" le nom (balise "title") de la couche (spécifier un alias).

**Comment by pelord** [comment]
Je ne crois pas que c'est une bonne idée! Ca va devenir rapidement l'enfer a gérer!! On y avait pensé lors du développement.
@hugbe8

**Comment by ameliebernier** [comment]
Mais ça pourrait être optionnel non?

**Comment by pelord** [comment]
Oui, mais ca sent vraiment pas bon pour maintenir cela!!

**Comment by mbarbeau** [comment]
Ajouter d'autre params comme metadata url (demande @pelord )

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/799
