### ISSUE TITLE
Lors de l'ajout d'une couche par la recherche, le système ne donne pas la possibilité de configurer le queryFormat (en suspens, semble corrigé)

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#516]
Nous voudrions le mettre en htmlgml2, et quelques couches en html.

**Comment by coulo3** [comment]
![image](https://user-images.githubusercontent.com/56965082/93782619-ca236580-fbf8-11ea-8c6a-2c00fbe60574.png)

**Comment by josee666** [comment]
@mbarbeau il me semble que ce problème était corrigé... Avant, je crois que c'était correct, que les couches ajoutées via la recherche avaient un queryformat en htmlgml2 comme ce que nous voulons... Modification lors de la maj??

**Comment by mbarbeau** [comment]
Ça me semble correct de mon côté (c'est en html, défini dans la config dans la section de l'outil ilayer)

**Comment by mbarbeau** [comment]
![image](https://user-images.githubusercontent.com/2047019/93793010-3f486800-fc04-11ea-84c4-c8a5fdb560ba.png)
