### ISSUE TITLE
Liste des couches : Avoir un bouton pour zoomer sur l'étendue de la couche

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#518]
À partir de la liste des couches dans l'onglet carte, ce serait intéressant d'avoir un bouton permettant de zoomer sur l'étendue de la couche. Ça inclut aussi les couches vectorielles.

**Comment by pelord** [comment]
Peut-être mettre la config par défaut a "false" pour ne pas faire apparaitre le bouton pour toutes les couches.. car ce concept est peu intéressant pour les couches provinciales. Du moins y réfléchir.
