### ISSUE TITLE
Perte de l'ordre des couches à l'export-import d'un contexte

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#529]
Quand on exporte le contexte et importe par la suite, les couches nouvelles sont toutes en fin de légende.
Autant ajout de couche via recherche que catalogue.
Le comportement souhaité serait de conserver l'ordre des couches du contexte lors de l'export.
![export+import](https://user-images.githubusercontent.com/56965082/96137661-e601ea80-0eca-11eb-946e-44a5e168b621.gif)

**Comment by mbarbeau** [comment]
corrigé dans la version 1.5.0

**Comment by mbarbeau** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/commit/4e3dd070f80dc7de1765fc9ea9c03b58fffdfbf0

**Comment by coulo3** [comment]
Corrigé dans la 1.5
