### ISSUE TITLE
Recherche - Le X ne supprime pas le polygone bleu de l'élément après une autre action

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#531]
Auparavant le X disparaissait si par exemple on allumait un contexte.
Maintenant il est là mais ne fonctionne pas.

![X_recherche](https://user-images.githubusercontent.com/56965082/96267915-5de91700-0f96-11eb-8946-18dda52bb9ee.gif)

**Comment by mbarbeau** [comment]
je crois que le problème n'est pas présent dans la version 1.5

**Comment by coulo3** [comment]
Réglé dans la 1.5
