### ISSUE TITLE
Problème filtre temporel lors d'ajout de couche par catalogue ou recherche

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#539]
![image](https://user-images.githubusercontent.com/56965082/96871786-bdd13900-1440-11eb-96c9-cf8b0401194d.png)

**Comment by pelord** [comment]
Je crois que tu devrais être plus précis concernant le problème :) .

**Comment by coulo3** [comment]
![image](https://user-images.githubusercontent.com/56965082/96874388-12c27e80-1444-11eb-921b-5ce420dbb77f.png)

Ceci est ce que nous voulons.  Le bon filtre s'affiche lorsqu'on passe par les contextes.
La configuration qui a été définie en années du timeFilter ne s'applique plus depuis la version 1.4 lors de l'ajout des couches via recherche et catalogue.

Catalogue:

{
            "id": 2,
            "title": "Données écoforestières",  
            "showLegend":false,
            "timeFilter": {
                "min": "1890",
                "max": "2019",
                "style": "calendar",
                "range": true,
                "step": 63072000000,
                "type": "year"
            },
            "composite": [
              {
                "id": "2",
                "url": "@host/ws/mffpecofor.fcgi",
                "sourceOptions": {
                    "crossOrigin": "anonymous",
                    "queryFormat": "htmlgml2",
                    "queryHtmlTarget": "iframe",
                    "type": "wms",
                    "optionsFromCapabilities": true
                },
                "regFilters": ["^ca_feux$","^ca_pertu_autre$","^ca_non_fores$","^ca_interv_fores$","^ca_interv_recente$"],
                "groupImpose": {
                    "id": "perturbations", "title": "Perturbations naturelles et anthropiques"}
              }
        ]
        }

**Comment by josee666** [comment]
Pour l'ajout via catalogue: 
la configuration du timeFilter n'est pas au bon niveau. Elle doit être à l'intérieur de source option à l'intérieur du catalogue composite. Une précision sera ajouté à la doc pour clarifier ceci.

**Comment by josee666** [comment]
Pour l'ajout via la recherche:
Les configurations seront populés par API option. 
NB: pour min/max si les valeurs ne sont pas définit, le système ira le chercher dans le getCapabilities.
(a ajouter @mbarbeau pour /mffpecofor.fcgi
layer: ca_interv_recente, ca_feux, ca_non_fores, ca_pertu_autre, ca_interv_fores
config:
"timeFilter": {
                "style": "calendar",
                "range": true,
                "step": 63072000000,
                "type": "year"
            },
