### ISSUE TITLE
Importation de contexte: Ne s'ouvre pas a l'importation en l'absence de fond de carte (couche de base)

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#544]
A l'importation d'un contexte, celui-ci s'affiche vide s'il ne contient pas de couche de fond.  On doit activer un autre contexte et revenir dans celui importé pour qu'il s'affiche correctement.  En présence d'un fond de carte (ou base layer), le contexte s'affiche.

![import_contexte](https://user-images.githubusercontent.com/56965082/97347085-afc95100-1862-11eb-9c0b-49a271147026.gif)

**Comment by coulo3** [comment]
Rare qu'on exporte un contexte sans fond.  Priorité moyenne.

**Comment by pelord** [comment]
@drekss @gignacnic

**Comment by coulo3** [comment]
J'ai mis "removable": False sur les fonds de carte.
