### ISSUE TITLE
Impression : Possibilité d'avoir la légende sur la même image / même page que la carte (pdf)

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#547]
Avoir la possibilité que l'image s'affiche à côté de la carte dans une cartouche par exemple (pour les images ou les pdf)

**Comment by pelord** [comment]
Si vous travaillez là-dessus. est-ce que vous pouvez adresser ce pb au passage?
https://github.com/infra-geo-ouverte/igo2/issues/387

**Comment by josee666** [comment]
Il faut penser au cas de figure ou il y aura plusieurs légendes, comment ferra t'on la disposition de celle-ci? Si la légende contient 15 classes ou s'il y a 10 couches avec légendes actives lors de l'impression.
