### ISSUE TITLE
le filtreOGC est lancé sur une couche non visible avec configuration 2layers ensemble

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#550]
Avec 2 layers dans le param layer, le filtre est lancé sur les 2 layers même si l'un d'eux est non visibles.
Il ne faudrait pas envoyer la requete de filtre au service sur le layer qui n'est pas visible a cette échelle.

Exemple le layer1 est visible seulement a 50000 et le layer2 à l'échelle du QC. 
J'ai mis les 2 layers dans dans la couche ("layers": "layer1,layer2")

Si je lance la requete de filtre a l'échelle 2000000, IGO envoie au service une requete de filtre sur chaqu'un des layers même si le layer1 n'est pas visible à cette échelle

exemple de config
{
        "visible": false,
        "metadata": {
            "extern": false
        },
        "sourceOptions": {
            "crossOrigin": "anonymous",
            "queryFormat": "html",
            "queryHtmlTarget": "iframe",
            "url": "@host/ws/mffpecofor.fcgi",
            "params": {
                "layers": "sh_reg_eco,sh_soudom_bio",
            },
            "type": "wms",
            "ogcFilters": {
                "enabled": true,
                "editable": true,
                "allowedOperatorsType": "basic"
            },

            "sourceFields": [
                {"name": "ZONE_VEGd", "alias": "Zone de végétation", "values": ["Boréale", "Tempérée nordique"]},
                {"name": "SZONE_VEGd", "alias": "Sous-zone de végétation", "values": ["Forêt décidue", "Forêt boréale continue", "Forêt mixte"]},
                {"name": "dom_bio", "alias": "Domaine bioclimatique", "values": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]},
                {"name": "sdom_bio", "alias": "Sous-domaine bioclimatique", "values": ["1","2E","2O","3E","3O","4E","4O","5E","5O","6E","6O"]},
                {"name": "reg_eco", "alias": "Région écologique", "values": ["1a","2a","2b","2c","3a","3b","3c","3d","4a","4b","4c","4d","4e","4f","4g","4h","5a","5b","5c","5d","5e","5f","5g","5h","5i","5j","5k","6a","6b","6c","6d","6e","6f","6g","6h","6i","6j","6k","6l","6m","6n","6o","6p","6q","6r"]}
            ]      
        }
    },

* **Igo Version:**
1.5

**Comment by coulo3** [comment]
Solution de contournement

**Comment by pelord** [comment]
TU peux faire un linkedLayer 
https://igo2.readthedocs.io/fr/latest/properties.html#linkedlayersoptions
