### ISSUE TITLE
Outil d'importation: Détecter automatiquement la projection des shapefiles

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#555]
Quand un utilisateur importe un shapefile, l'outil devrait détecter automatiquement le système de coordonnées

**Comment by pelord** [comment]
PR en cours pour les geojson et gml, mode drag and drop
https://github.com/infra-geo-ouverte/igo2-lib/pull/771

**Comment by pelord** [comment]
@PhilippeLafreniere18  Lié a l'api.. pas a igo.. donc on ferme.
