### ISSUE TITLE
Outil d'importation: Ajouter les EPSG aux projections Lambert comme les autres?

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#560]
![image](https://user-images.githubusercontent.com/56965082/98862871-949b3b80-2435-11eb-8efb-3f9157da8faa.png)

**Comment by pelord** [comment]
Il faut modifier ton alias dans ta config.json ou environnement

https://github.com/infra-geo-ouverte/igo2/blob/50dd8422a054550917a2e28079da6d57c59fa944/src/environments/environment.ts#L212

**Comment by coulo3** [comment]
Est-ce que je dois mettre la "def" dans mes paramètres ou si je peux mettre seulement "code" et "alias" ?

"projections": [ 
           { 
             "code": "EPSG:32198", 
             "alias": "Quebec Lambert (EPSG:32198)"
           }, 
           { 
            "code": "EPSG:3798", 
            "alias": "MTQ Lambert"
           } 
         ],

**Comment by pelord** [comment]
la def est très importante. 
réfère toi a 
http://epsg.io/32198
![image](https://user-images.githubusercontent.com/7397743/98865196-0e80f400-2439-11eb-8614-ad8437fd56de.png)

**Comment by coulo3** [comment]
ok je me demandais si je pouvais l'omettre et qu'il la prendrait par défaut

**Comment by pelord** [comment]
Non.

**Comment by coulo3** [comment]
Réglé merci
