### ISSUE TITLE
Liaison Organisme Québecois

### ISSUE THREAD

**Issue by YannTrudelToumoro** [infra-geo-ouverte/igo2#566]
Bonjour,
nous sommes présentement en développement pour un organisme du gouvernement Québécois qui utilisera la carte.

Nous aimerions savoir s'il était possible d'augmenter le nombre de requête limite à l'API qui donne les images du fond de carte?

L'application sera éventuellement dévoilée au grand public, et nous ne pourrons permettre un si petit nombre de requête.

Merci!

**Comment by mbarbeau** [comment]
Suite dans une conversation privée
