### ISSUE TITLE
Avoir la possibilité d'ajouter d'autres puces de précisions dans l'outil import-export

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#569]
![image](https://user-images.githubusercontent.com/56965082/104501135-4deccd80-55ad-11eb-8baf-223e3533d95c.png)

On peut pas ajouter une 4e puce dans FO.
c'est pour ça que j'ai mis "la symbologie sera attribuée.." dans la puce 3 au lieu d'en faire une autre.

**Comment by ameliebernier** [comment]
Intéressant parce que selon les types de données disponible dans une instance, les capacités de l'outil ne sont pas les mêmes. Par exemple si l'instance ne contient pas de couches WFS, l'export des couches n'est pas possible

**Comment by pelord** [comment]
@josee666  valide svp

**Comment by pelord** [comment]
sera disponible dans 1.13.1
