### ISSUE TITLE
Vector tiles : pouvoir représenter une même couche avec plusieurs symbologies

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#571]
Pourvoir faire pour les couches vector tiles le même principe qu'avec les WMS : Plusieurs symbologies différentes peuvent être prédéfinies pour la couche, et l'utilisateur peut sélectionner l'une ou l'autre

**Comment by ameliebernier** [comment]
@matrottier

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/issues/356

**Comment by PhilippeLafreniere18** [comment]
à fermer ? @pelord

**Comment by pelord** [comment]
On pourrait le ouvrir au besoin.
