### ISSUE TITLE
Outil d'ajout de WMS externes

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#572]
Avoir un outil qui permet de parcourir un catalogue WMS externe qui n'est pas dans le catalogue principal de l'instance. Pourrait permettre l'ajout de n'importe quelle adresse OU utiliser une liste prédéfinie

**Comment by pelord** [comment]
Contraintes CORS/CSP a anticiper.

**Comment by ameliebernier** [comment]
Oui c'est pourquoi il serait utile d'avoir une liste prédéfinie (avec seulement les URL débloqués)

**Comment by pelord** [comment]
Inclus dans la version 1.7.0

paramètres a configurer coté outil de catalogue:

- addCatalogAllowed= permet d'activer ou non le formulaire d'ajout de catalogues. FORMULAIRE ABSENT PAR DÉFAUT.
- predefinedCatalogs = liste préconfigurée de catalogue pouvant etre ajouté dans le formulaire.


![image](https://user-images.githubusercontent.com/7397743/115917583-7b66d400-a444-11eb-8bbc-ab29731cd23a.png)

**Comment by pelord** [comment]
![image](https://user-images.githubusercontent.com/7397743/115918395-78b8ae80-a445-11eb-83c6-cb96a7a72000.png)
