### ISSUE TITLE
Pouvoir faire plusieurs couches avec l'outil de dessin

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#573]
Actuellement tous les croquis vont dans une même couche, mais il pourrait être intéressant pour l'utilisateur de pouvoir créer différentes couches et de les nommer à sa guise. Le nom pourrait suivre lors de l'exportation.

**Comment by PhilippeLafreniere18** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/1081
