### ISSUE TITLE
Outil de conversion de coordonnées

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#574]
Actuellement la recherche de coordonnées présente une conversion dans quelques systèmes de coordonnées, cependant il pourrait y avoir un outil dédié à cela qui permettrait de supporter un plus grand nombre de systèmes de coordonnées. Liste à venir

**Comment by pelord** [comment]
Lié au projections enregistrées dans l'applications. 
https://github.com/infra-geo-ouverte/igo2/blob/82a2366a8f34981fc3c385caf12d344048b7b8a4/src/environments/environment.github.ts#L89

**Comment by pelord** [comment]
@ameliebernier Est-ce suffisant?

**Comment by ameliebernier** [comment]
Outil n'ets plus nécessaire pour nous, nous allons ajouter les systèmes de coordonnées manquants dans les résultats de recherche de coordonnées
