### ISSUE TITLE
Outil de dessin version 2.

### ISSUE THREAD

**Issue by gignacnic** [infra-geo-ouverte/igo2#578]
Résumé des demandes:
- Possibilité d'appliquer une style unique par élément de dessin... pas seulement une couleur pour tous les éléments/features 
- Drôle d'effet sur le cercle lors du zoom...
- Mettre un œil dans l'outil pour cacher la couche (pas seulement dans le "map-tools")
- Mettre un œil sur les éléments/feature (dans le tableau au bas)... pour choisir quel élément/feature montrer... sans nécessairement le supprimer.
- Mettre un délai de x millisecondes entre le clic et l'overlay, pour la saisie de l'étiquette d'un point.
- À revoir peut être, la couleur de l'élément coché/sélectionné est pratiquement pareil que la couleur attribué par défaut. Difficile de voir d'un coup d'oeil sur la carte l'élément sélectionné...
- Aussi, il me semble y avoir beaucoup de perte d'espace pour la sélection de couleur...
- Peut être ajuster la largeur du sélecteur de couleur pour éviter l'apparition d'un scroll bar horizontal. C'est pas grand chose, mais quand on clic sur le scroll bar on perd le sélecteur...
- Pouvoir modifier la géométrie et l'étiquette.
- La font du popup ''Étiquette" n'est pas correct

**Comment by ameliebernier** [comment]
Est-ce qu'on peut indiquer les principales amélioration qui seront faites? Afin de mieux répondre aux questions de nos utilisateurs, merci!

**Comment by gignacnic** [comment]
- Possibilité d'appliquer une style unique par élément de dessin... pas seulement une couleur pour tous les éléments/features (Phase 2)
-  Drôle d'effet sur le cercle lors du zoom...
- Mettre un œil dans l'outil pour cacher la couche (pas seulement dans le "map-tools")
- Mettre un œil sur les éléments/feature (dans le tableau au bas)... pour choisir quel élément/feature montrer... sans nécessairement le supprimer.
- Mettre un délai de x millisecondes entre le clic et l'overlay, pour la saisie de l'étiquette d'un point.

**Comment by pelord** [comment]
La solution.. a mon avis, pour "Drôle d'effet sur le cercle lors du zoom..." serait de transformer le cercle en polygone
Ceci réglerais également l'exportation du cercle qui est faite en point/rayon.

**Comment by majme1** [comment]
À revoir peut être, la couleur de l'élément cocher/sélectionné est pratiquement pareil que la couleur attribué par défaut. Difficile de voir d'un coup d'oeil sur la carte l'élément sélectionné...
![image](https://user-images.githubusercontent.com/57358502/106753112-3bd4dc80-65f9-11eb-9064-1e9dbd47743a.png)

**Comment by majme1** [comment]
Aussi, il me semble y avoir beaucoup de perte d'espace pour la sélection de couleur... 
![image](https://user-images.githubusercontent.com/57358502/106753407-a0903700-65f9-11eb-8c7e-4c41c8f3c238.png)

**Comment by majme1** [comment]
Peut être ajuster la largeur du sélecteur de couleur pour éviter l'apparition d'un scroll bar horizontal. C'est pas grand chose, mais quand on clic sur le scroll bar on perd le sélecteur...

https://user-images.githubusercontent.com/57358502/106755418-1b5a5180-65fc-11eb-9219-4459589628dd.mp4

**Comment by mbarbeau** [comment]
- Pouvoir modifier la géométrie et l'étiquette.
- La font du popup ''Étiquette" n'est pas correct

**Comment by PhilippeLafreniere18** [comment]
J'ai sous-divisé l'ensemble des demandes en 4 issues pour faciliter l'avancement de la phase 2 de l'outil de dessin : 
#646 #647 #648 #649 

Je propose que l'on ferme celui-ci, est-ce que ça vous irait ?
