### ISSUE TITLE
Possibilité de faire une recherche par no. de feuillet

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#604]
Ajouter la possibilité de faire une recherche par no. de feuillets (250K, 50K, 20K), UA, UG.
Évaluer la possibilité de faire une recherche par geocode, numéro de photo selon l'effort à mettre versus le besoin qui est moindre.

**Comment by josee666** [comment]
pour UA et UG elles ne sont pas dans notre service, ne sont pas disponibles en WFS et créer via arcGisServer. Dans ces conditions il est dificilement pensable de créer un service de recherche sur ces couches.

**Comment by josee666** [comment]
inclus dans 1.7.2
