### ISSUE TITLE
Partage de carte:  Les paramètres d'affichage ne sont pas conservés

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#608]
Lors du partage d'une carte, les couches présentes dans la carte sont différentes dans le lien partagé.
- Les couches supprimées dans un contexte réapparaissent dans la carte partagée;
- Dans certains cas, ça affecte les couches affichées vs masquées.

Exemples:

![Clipboard - 20 avril 2021 10_18](https://user-images.githubusercontent.com/56965082/115427849-d0e67b00-a1cf-11eb-87e0-cfd725cd627d.png)

**Comment by pelord** [comment]
Dans notre version, j'ai ajouté un paramètre pour controler les couches qui sont présentes par défaut.. Relancez moi en privé si ca vous intéresse.

Une autre solution, serait de mettre les couche de base, avec l'option de layer "removable": false

**Comment by coulo3** [comment]
Semble arrangé en après avoir mis les couches de base à removable = False

**Comment by pelord** [comment]
Sinon j'ai une solution coté code !
