### ISSUE TITLE
Problème avec les dates de début/fin dans le filtre temporel du filtre attributaire (paramètres filters)

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#624]
La date de début du filtre n'inclut pas la date paramétrée.  Voici mes paramètres:
![image](https://user-images.githubusercontent.com/56965082/118650707-bdb8d200-b7b2-11eb-90c2-14b3c2341a3f.png)
Le stepDate est à "P1Y" pour que le calendrier propose des années au lieu des jours.

Dans la bd, le champ "année_date" est peuplé ainsi (pour l'exemple, les polygones ont comme date 2015-01-01):
![image](https://user-images.githubusercontent.com/56965082/118648435-644fa380-b7b0-11eb-9129-50f6adb0a7dd.png)

Si j'applique le filtre sur date de début = 1/1/2015:
![image](https://user-images.githubusercontent.com/56965082/118648861-d9bb7400-b7b0-11eb-9b3f-16e500ab8a31.png)

Les polygones disparaissent. Je dois mettre l'année 2014 pour que ça s'affiche:
![image](https://user-images.githubusercontent.com/56965082/118649639-bba24380-b7b1-11eb-972f-1471965b431f.png)

Pour la date de fin même chose, si je mets 12/31/2014, les polygones 2015 restent affichés:
![image](https://user-images.githubusercontent.com/56965082/118650279-41be8a00-b7b2-11eb-8520-629141c00fb2.png)

Je dois mettre l'année 2013 pour qu'ils se désaffichent:
![image](https://user-images.githubusercontent.com/56965082/118650404-6d417480-b7b2-11eb-82ff-30a3e29e4606.png)

**Comment by josee666** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/907
