### ISSUE TITLE
Édition de données dans IGO

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#630]
Avoir un interface d'édition de données dans IGO.

Le côté API serait séparé d'IGO mais devrait répondre à un format particulier.

**Comment by pelord** [comment]
Est-ce que la notion de hors-ligne sera considérée?

**Comment by ameliebernier** [comment]
Non, pas dans cette version

**Comment by gignacnic** [comment]
De notre côté, nous allons regarder cette voie, hors ligne, à l'automne prochain.
