### ISSUE TITLE
Table d'attributs WMS: La sélection d'un élément ne se répercute pas dans la table

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#635]
Il serait pratique qu'un élément sélectionné dans la carte soit mis en surbrillance dans la table d'attributs:

![image](https://user-images.githubusercontent.com/56965082/120380398-1ded5f00-c2ef-11eb-9aee-523d80fc6245.png)

**Comment by pelord** [comment]
Je vais regarder cela mais je n'ai pas ce bug dans mes couches wms/wfs

**Comment by pelord** [comment]
Je vais investiguer...

**Comment by josee666** [comment]
Éffectivement, sur un geojson ajouté par import la sélection fonctionne bien d'un sens comme dans l'autre. Possiblement relié a https://github.com/infra-geo-ouverte/igo2-lib/issues/875
comme les feature sont dédoublées, il se peut qu'il y ai probleme a selectionner les id...

**Comment by josee666** [comment]
Le problèeme viens du fait que le output est définie en geojson. De cette facon, selon la config de notre service web, il n'y a pas de id au premier niveau dans les objet retourné, ce qui semble causé problèeme a IGO.
Bref simplement ne pas mettre le outputFormat : geojson.

Cette config ne cause plus de problème de dédoublement d'entité:
 {     
        "title": "Photos obliques WFS-WMS",
        "visible": true,
        "workspace": {
            "enabled": true,
            "maxResolution": 300
          },
            "sourceOptions": {
              "queryable": true,
              "queryTitle": "test",
              "crossOrigin": "anonymous",
              "queryFormat": "htmlgml2",
              "queryHtmlTarget": "iframe",
              "type": "wms",
              "optionsFromCapabilities": true,
              "url": "/ws/mffpecofor.fcgi",
              "params": {
                "layers": "nord_photo_oblique",
                "version": "1.3.0"
              },
              "urlWfs": "/ws/mffpecofor.fcgi",
              "paramsWFS": {
                "featureTypes": "nord_photo_oblique",
                "fieldNameGeometry": "geometry",
                "maxFeatures": 1000,
                "version": "2.0.0"
              },
          "sourceFields": [
            {"name": "LATITUDE", "alias": "lat"},
            {"name": "LONGITUDE", "alias": "lon"},
            {"name": "NOM_PHOTO", "alias": "nom"} 
        ] 
        }
    }
