### ISSUE TITLE
MidpointTooltip est affiché si on ne finit pas la construction

### ISSUE THREAD

**Issue by almat65** [infra-geo-ouverte/igo2#637]
* **Igo Version:**
master 1.7.2 et+

dans l'onglet Mesure après les tentatives de construction des distances ou des superficies (interrompues par la touche Echap), des tooltips continuent d'être affichées.
![problème](https://user-images.githubusercontent.com/84472530/121195663-cba3c500-c83d-11eb-9a43-87d5f308e86b.JPG)

**Comment by pelord** [comment]
Corrigé dans https://github.com/infra-geo-ouverte/igo2-lib/pull/970

version 1.11 a venir.
