### ISSUE TITLE
Menu contextuel sur iOS

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#645]
**Please tell us about your environment:**

iOS

* **Igo Version:**
1.7 +

Le menu contextuel pour accéder aux outils google ne s'ouvre pas lorsque sur iOS, on touche/maintient l'écran.

![image](https://user-images.githubusercontent.com/7397743/122787374-4380df00-d283-11eb-90c4-65cea6858a44.png)

Le comportement est bon sur Android.

**Comment by majme1** [comment]
C'est simulé, mais quand je maintiens le cick de la souris sur l'écran pour simuler un "hold", y ne se passe rien dans Forêt ouverte, alors qu'un repère est ajouté dans google maps avec la même simulation d'iphone.

![image](https://user-images.githubusercontent.com/57358502/122788984-d706df80-d284-11eb-953a-5175a0aa6f1b.png)
![image](https://user-images.githubusercontent.com/57358502/122789194-09b0d800-d285-11eb-95cb-9d55e320f0b0.png)

**Comment by pelord** [comment]
Leaflet a le même genre de pb
https://github.com/Leaflet/Leaflet/issues/6817

Il y aurait ceci comme solution potentielle
https://www.npmjs.com/package/long-press-event

**Comment by pelord** [comment]
Références
https://medium.com/@ankit.rana.1195/angular-long-press-directive-with-rxjs-c3d6a3eb8c60
https://stackoverflow.com/questions/52260282/how-to-get-long-tap-right-click-or-such-events-on-openlayers5
https://stackblitz.com/edit/rxjs-longpress-event

**Comment by pelord** [comment]
dans la version 1.9

**Comment by pelord** [comment]
@majme1 réglé dans 1.13.2
