### ISSUE TITLE
Outil de dessin: Afficher/Cacher les dessins

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#648]
Ajout d'un oeil permettant de masquer/démasquer la couche à partir de l'outil (pas seulement de l'onglet carte)

Ajout d'un oeil permettant de masquer/démasquer un élément à partir du tableau des dessins

**Comment by pelord** [comment]
Faire de même pour l'outil d'itinéraire svp :)

**Comment by pelord** [comment]
dans la version 1.9
