### ISSUE TITLE
Outil de dessin: Améliorations interface

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#649]
Améliorations notées au niveau de l'interface:

 - Ajustement du sélecteur de couleur pour éviter l'apparition du scroll bar horizontal
 - Ajout d'un petit délai pour la saisie de l'étiquette
 - Harmoniser la couleur par défaut ainsi que celle de la sélection pour éviter de les confondre
 - Transformer le cercle en polygone pour éviter le comportement étrange au zoom

**Comment by pelord** [comment]
transformer le cercle en polygone pour éviter le comportement étrange au zoom ...

ce point est aussi très important lors de l'export de la couche, la donnée exporté de type cercle, est un point avec un rayon.. pas idéal!
