### ISSUE TITLE
Outil d'itinéraire: Afficher/Masquer les couches 

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#650]
Ajout d'un oeil permettant d'afficher / masquer les couches de données d'itinéraire (tracé et arrêts) à partir de l'outil (pas seulement à partir de l'onglet carte)

**Comment by PhilippeLafreniere18** [comment]
@pelord est-ce aussi nécessaire de pouvoir afficher/masquer une seule des deux couches à la fois (tracés ou arrêts) ?

**Comment by pelord** [comment]
je dirais que pour cet outil.. on fait 1 œil pour les gouverner tous!

**Comment by pelord** [comment]
dans la version 1.9
