### ISSUE TITLE
Un mauvais lien vers un service Web (mauvais non de couche) n'affiche pas de message d'erreur

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#653]
La couche de chemins dans FO ne s'affichait pas en prod, mais aucun message d'erreur n'apparaissait.  Des utilisateurs croient que la couche est vide, ou qu'ils ne sont pas à la bonne échelle d'affichage.
Pour reproduire, faire une modif dans le nom d'un layer.  La couche ne s'affiche plus, mais sans message rouge.

Config de la couche:
{
        "title": "Chemins",
        "visible": true,
        "baseLayer": false,
        "legendOptions": {
            "display": false
          },
        "sourceOptions": {
          "crossOrigin": "anonymous",
          "url": "https://servicescarto.mern.gouv.qc.ca/pes/services/Territoire/AQreseauPlus_WMS/MapServer/WMSServer",
          "params": {
            "version": "1.3.0",
            "layers": "Autoroute [35M - 750K],Autoroute [50K - 8K],Autoroute [750K - 50K],Autoroute [8K - 1]",
            "srs": "ESPG:3857"
          },
          "type": "wms"
        }
    },

**Comment by josee666** [comment]
sourceOptions:  optionsFromCapabilities = false (a true le comportement est ok)
si le layers dans param est mauvais la couche s'affiche dans le layer liste mais la couche ne s'affiche pas dans la carte.
aucun message d'erreur qui indique un problème donc l'utilisateur crois que la couche est vide.
![image](https://user-images.githubusercontent.com/32003632/128191979-17fb5652-54ee-4a60-ad19-b101b16293cd.png)
