### ISSUE TITLE
Outil de mesure: Problème avec la couche ajoutée dans l'onglet carte et celle présente dans l'outil

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#654]
Lorsque l'on supprime ou que l'on cache la couche dans l'onglet Carte, celle-ci réapparaît lorsque l'on réouvre l'outil de mesure, car elle est toujours présente dans le tableau des mesures de l'outil.

Il faudrait que la mesure soit supprimée du tableau si elle est supprimée de la carte et qu'elle demeure cachée si elle a été mis ainsi à partir de l'onglet Carte.

**Comment by majme1** [comment]
C'est le même comportement avec l'outil dessin et la couche créée dans Ma carte.

**Comment by pelord** [comment]
dans la version 1.9
