### ISSUE TITLE
Export: Permettre de combiner plusieurs fichiers en un

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#665]
Permettre de combiner le résultat de l'export en un seul fichier quand plusieurs couches sont sélectionnées.

**Comment by PhilippeLafreniere18** [comment]
Resolve for CSV ; separator : https://github.com/infra-geo-ouverte/igo2-lib/pull/949

**Comment by pelord** [comment]
Fait. 1.10
