### ISSUE TITLE
Outil de dessin : Créer un cercle avec un rayon prédéfini

### ISSUE THREAD

**Issue by almat65** [infra-geo-ouverte/igo2#666]
It will be useful to create a tool to draw a circle with a predefined radius.
![image](https://user-images.githubusercontent.com/84472530/131134086-e99f6524-004e-4688-ba59-6fd2d8dcbbec.png)

**Comment by PhilippeLafreniere18** [comment]
feat in 1.14 https://github.com/infra-geo-ouverte/igo2-lib/pull/1090
