### ISSUE TITLE
Le bouton de géolocalisation 

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#668]
* **Igo Version:**

1.5+ (ca fait longtemps)

Le bouton de localisation, ne fonctionne pas très bien. le comportement du bouton est difficile a saisir. Il y a une option utilisée pour faire le tracking de la vue.. celui ci fonctionne bien. De plus, il n'est pas possible d'enlever le polygone de localisation une fois que le bouton a été utilisé

La proposition.
Transformer le bouton en 2 états
![image](https://user-images.githubusercontent.com/7397743/135271590-e250340c-f8a4-486c-8af7-6c0356777dba.png)
La localisation inactive et active.

Pour activer le zoom sur position de localisation serait une option "cachée" dans Advanced Map tools..... Évidemment, elle serait pilotable par une configuration de contexte (comme c'est déjà le cas!). Le statut de cette variable serait surement écrite dans le "storage" du fureteur pour utilisation ultérieure. 

@josee666 
@obegin3

Je le met dans le roadmap 1.11.. on le reportera au besoin.

**Comment by PhilippeLafreniere18** [comment]
@pelord closed ?

**Comment by majme1** [comment]
voir issue 814 pour le tooltip du bouton lorsqu'activée
