### ISSUE TITLE
Les tours interactifs dans les outils sont instables

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#677]
Lorsque j'ouvre le tour interactif de l'outil import-export, j'ai 11 boîtes.
![image](https://user-images.githubusercontent.com/56965082/137021602-306a1522-687e-4322-a499-fdc26a093545.png)

Si je le referme, va ouvrir le tour interactif principal, et reviens dans le tour de l'outil, une boîte a disparu. Le tour est décalé et ne pointe plus toujours sur les bons éléments.
![image](https://user-images.githubusercontent.com/56965082/137021821-082fdba6-615b-4fda-b30c-ca6283b9c80c.png)

**Comment by josee666** [comment]
dans la boite1 du tour, vous selectionnez: 
 "element": "div.mat-tab-labels div#mat-tab-label-0-0"

mais lorsqu'on revient la 2e fois, l'élément mat-tab-label-0-0 n'existe plus il s'apelle maintenant mat-tab-label-1-0, c'est pour cette raison que le tour passe de 11 a 10 boite et ne selectionne plus la 1e boite. 
Il vaut mieux éviter de sélectionner des éléments creé par material avec des no, les no sont sujet a changement lorsque l'interface change.

Solution: aller chercher l'élément parent qui lui ne change pas de nom et selectionner son 1er enfant
"element" : "div.mat-tab-list .mat-tab-labels :first-child",

ref pour les selecteurs css ici: https://www.w3schools.com/cssref/css_selectors.asp
