### ISSUE TITLE
Time and ogc filters: deactivate time filter button in calendar mode

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#694]
Actually, there is no button to deactivate time filter on a layer. 

Could be great to be able to activate/deactivate just like in ogc filter attribute.

**Comment by pelord** [comment]
there is one enable disable for slider, year type

![image](https://user-images.githubusercontent.com/7397743/143062564-ef30bf80-5bd6-4e8f-bfcd-922dfbc25f71.png)

**Comment by PhilippeLafreniere18** [comment]
Yes, should be there for "calendar" mode also

**Comment by pelord** [comment]
I think for every mode.

**Comment by josee666** [comment]
same issus?? https://github.com/infra-geo-ouverte/igo2/issues/328

**Comment by PhilippeLafreniere18** [comment]
Indeed, very related ! #328 only mention the reset, but it should also be possible to deactivate entirely. I propose to combine the two ?

**Comment by josee666** [comment]
reset and desactivate will have same comportement? Whats the difference?
So why you would deactivate filter more than reset it?  
if you do not want filter, just not show with param:
"timeFilterable": false,

**Comment by PhilippeLafreniere18** [comment]
In my opinion, reset keep the filter activated but reset to the initial value (the one that is predefined in the sourceOptions). 
Then, deactivate disable the filter. Actually, when a time filter is applying on one layer, there is no way to juste "don't apply it"
