### ISSUE TITLE
Messages pour les couches ouverte a l'entré du context repeté 4 fois

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#710]
Vérifier d'ou viens le [4]

Le 4 est là juste quand tu ouvres le contexte. si tu ferme et ouvre la couche à nouveau le message est ok.

![image](https://user-images.githubusercontent.com/56965082/146220762-9ad17df3-8239-45df-ada1-062a556bbeff.png)

**Comment by pelord** [comment]
C'est le nombre de fois que le message est répété... Il indique combien de fois le message a été envoyé plutot que de le dupliquer.

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/blob/a108cac2d821ad85c4669538bc723fe65746b48d/packages/core/src/lib/message/message.module.ts#L20

**Comment by josee666** [comment]
le message devrait etre lancé qu'une seule fois dans ce cas.
config: couche ouverte a l'entré dans le contexte et message sur la couche.

**Comment by josee666** [comment]
same problem on layer error [2]
![image](https://user-images.githubusercontent.com/32003632/146230820-fcef76dc-19f6-4525-a9d6-ff45bd15c2e7.png)

**Comment by josee666** [comment]
the param doen't work from context config.
simple fix:  just put the param countDuplicates:false in module here
https://github.com/infra-geo-ouverte/igo2-lib/blob/a108cac2d821ad85c4669538bc723fe65746b48d/packages/core/src/lib/message/message.module.ts#L20
@pelord ?

**Comment by pelord** [comment]
ok.

**Comment by coulo3** [comment]
Semble réglé
