### ISSUE TITLE
Exportation d'une carte avec une couche importée - Tourne en rond

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#711]
Problème lorsque l'on essaie d'exporter une carte avec une couche préalablement importée (geojson). Par exemple, après importation d'un geojson, tentative d'export de la carte en cochant cette couche = erreur, tourne en rond.

**Comment by pelord** [comment]
lié a #568

**Comment by josee666** [comment]
fix maintenant les couches locales importées ne sont plus présentées dans les couches possibles à exporter.
