### ISSUE TITLE
Vérification de la disponibilité de Google Street View

### ISSUE THREAD

**Issue by LAMM26** [infra-geo-ouverte/igo2#712]
Lors de la recherche d'une adresse ou lorsque l'utilisateur clique-droit sur la carte, il est possible de visualiser l'endroit dans Google Street View. Il arrive parfois que le service ne soit pas disponible à l'endroit voulu (ce qui montre une image noire). Il serait intéressant de vérifier a priori que le service est disponible. Voir les liens suivants pour des pistes de solution: 

https://stackoverflow.com/questions/2675032/how-to-check-if-google-street-view-available-and-display-message
https://developers.google.com/maps/documentation/javascript/reference?csw=1#StreetViewService

**Comment by pelord** [comment]
Nécessite les google service.
