### ISSUE TITLE
Inclure le PIV du gouvernement du Québec

### ISSUE THREAD

**Issue by marclonfo** [infra-geo-ouverte/igo2#723]
Nous voulons permettre d'ajouter à une instance IGO le PIV du gouvernement du Québec.

https://www.piv.gouv.qc.ca/normes-graphiques/

**Comment by pelord** [comment]
#398

**Comment by marclonfo** [comment]
l'option mapOverlay va être testé.

**Comment by marclonfo** [comment]
Nous allons tester l'option mapOverlay.
