### ISSUE TITLE
ogc-time date-mois-jour configuration du filtre

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#729]
Avec une config en jour -> pas de temps! 

probleme1: begin-> quand on selectionne une date du calendrier, on constate que la date passé a du temps (provenant de la convertion TZ) (5heures ou 4:59) se qui a pour consequence de ne pas faire afficher les evenements de cette journée qui serait survenu avant 5h ou qui ont inscrit ou 00.
probleme2:  end -> quand on selectionne une date du calendrier, la date est 1 journée de plus 🤔 avec un temps aussi... Donc on selectionne les évenements de la journée suivantes jusqu'a 4:59 dans le filtre.
exemple problem 1 de la demo IGO 1.10
![image](https://user-images.githubusercontent.com/32003632/152047654-9fe381e6-e4df-458e-bc43-edd11e4374ed.png)

date evenement: 2011-09-06T00:00:00Z
Date selectionnée:
debut: 2011-09-06
fin:  2022-02-01

call fait au service
begin: 2011-09-06T04:00:00.000Z
end:  2022-02-02T04:59:59.999Z

**Comment by josee666** [comment]
Je peux faire un fix simple- > avec une config en journée, pas de temps, on call le service sans temps:
le filtre du call sera: 
<Filter xmlns="http://www.opengis.net/ogc"><During><ValueReference xmlns="http://www.opengis.net/fes">date_observation</ValueReference><TimePeriod xmlns="http://www.opengis.net/gml"><begin><TimeInstant><timePosition>2014-02-26</timePosition></TimeInstant></begin><end><TimeInstant><timePosition>2014-02-26</timePosition></TimeInstant></end></TimePeriod></During></Filter>

Avec évenement ca passe bien et les évenement de la journée apparaissent bien.
@matrottier @pelord @PhilippeLafreniere18 ca vous vas?

**Comment by josee666** [comment]
crampe de temps au cerveau 🙃. 
la donnée est en UTC donc si exemple je veux couvrir la journée du 2 fevrier 2022 faut qu'on call
2 fev :5:00 - 3 fev 5:00
C'est quasiment correct juste le call de debut qui est a 4:00  (changement heure)
NB: C'est pas un peu melant pour les gens (et les dev un peu fatigué en fin de journée :) ) que l'évenement dont la date est le 2 fev n'apparaissent pas quand tu filtre sur la journée sur 2 fev?

**Comment by PhilippeLafreniere18** [comment]
Ouin, il faudrait effectivement que si c'est un picker sans choix d'heure, la journée sélectionnée soit inclue dans le filtre.
Dans ce cas, j'imagine que tu peux setter l'heure à midi ? Comme ça on s'assure tout le temps que le fuseau ne cause pas problème

**Comment by matrottier** [comment]
de mémoire l'appel est toujours fait en UTC et construit par OpenLayers. 
et faut toujours mettre un pas de temps. de X a Y.  
sinon le slider/calendrier devra se comporter comme un filtre attributaire
