### ISSUE TITLE
Amélioration de l'outil d'impression: PDF géoréférencés

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#747]
Amélioration à l'outil d'impression qui permettra de générer un fichier PDF géoréférencé pour utilisation hors ligne.
(Exemple: Avenza Maps)

**Comment by majme1** [comment]
C'est la fonctionnalité la plus en demande, qui revient à chaque fois qu'on présente Forêt ouverte. Les gens veulent pouvoir se créer une carte puis l'utiliser en forêt pour naviguer, notamment les chasseurs.

**Comment by pelord** [comment]
@josee666 on ferme?
