### ISSUE TITLE
workspace comportement sur clic dans la table attributaire

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#751]
* **Igo Version:**
igo 1.10

comportement problématique: 
lors d'un clic dans la table attributaire pafois l'entité selectionnée n'est pas visible dans la carte. Parfois caché par la table attributaire, parfois par le menu.

Comportement voulu:
1: ajouter un parametre (ou toujours par default??)  que la carte ce deplace et que l'entité soit visible dans la partie de carte visible pour utilisateur. Conserver le meme niveau de zoom
2: ajouter un bouton dans la table attributaire zoomOn pour zoom sur l'entité sélectionnée dans la table
(L'ajouter dans le actions.service ? il va s'ajouter dans les actions des ...)
![image](https://user-images.githubusercontent.com/32003632/159744095-b501abe9-fd00-45f5-9b62-a2e2c1ba2a55.png)

**Comment by pelord** [comment]
@josee666 on ferme?
