### ISSUE TITLE
Pourvoir modifier la couleur de sélection d'un feature lorque selectionné via table sans query affiché

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#765]
IGO v1.11

La couleur du polygon sélectionné est la couleur bleu par default.
Comportement souhaité:
pouvoir paramétrer la couleur de sélection via les config

![image](https://user-images.githubusercontent.com/32003632/164309023-0ba054e8-c5ad-4402-9a61-fb0d585c4bb8.png)

**Comment by PhilippeLafreniere18** [comment]
@josee666 closed ?
