### ISSUE TITLE
Dessin: améliorations pour la gestion des étiquettes

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#773]
- Pouvoir annuler le dessin au lieu de "Aucune étiquette" dans la fenêtre de confirmation
- Permettre l'édition des étiquettes par la table des entités 
- Pouvoir jouer sur le style de l'étiquette? (font, grosseur...)

**Comment by pelord** [comment]
@PhilippeLafreniere18 Choisir le champ a utiliser comme titre d'étiquette?

**Comment by pelord** [comment]
@PhilippeLafreniere18 @kalvinkhuu  Est-ce que vous avez regardé pour ajouter la coordonnée comme étiquette?

**Comment by PhilippeLafreniere18** [comment]
@pelord Pas encore, mais c'est toujours sur la todo !

**Comment by PhilippeLafreniere18** [comment]
@pelord https://github.com/infra-geo-ouverte/igo2/issues/802 for others
