### ISSUE TITLE
Impression + rotation

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#775]
**Please tell us about your environment:**

* **Igo Version:**
1.11.1+

L'impression avec rotation n'imprime pas avec la rotation.
Ajouter la fleche du nord?

**Comment by LAMM26** [comment]
Semble fonctionner dans 16.0.0-rc1. De mon côté par contre je ne suis pas capable de faire une rotation avec Alt+Shift+Drag. C'est peut-être lié à des raccourcis de mon clavier.
