### ISSUE TITLE
Ordonnancement des couches -- la barre de défilement ne suit pas. 

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#777]
* **Igo Version:**
1.11+

La barre de défilement ne suit pas la position de ta(tes) couche(s) lorsqu'elles sont déplacées. Dès qu'elle(s) sort(ent) de la zone , tu dois déplacer la barre pour savoir où elle(s) est(sont) rendu par rapport aux autres.

**Comment by pelord** [comment]
@PhilippeLafreniere18  réglé?

**Comment by PhilippeLafreniere18** [comment]
Non je ne pense pas, ce qui est réglé c'est la barre de défilement avec la sélection des résultats de recherche

**Comment by PhilippeLafreniere18** [comment]
Closed with https://github.com/infra-geo-ouverte/igo2-lib/pull/1116
