### ISSUE TITLE
Obtenir coordonnées : long-lat vs lat-long  

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#782]
* **Igo Version:**
1.11+

Présenter les coordonnées:

- long lat (situation actuelle) = -62.226173, 51.586891
- lat-long                               = 51.586891, -62.226173

Proposition. Placer une option dans options de recherche

![image](https://user-images.githubusercontent.com/7397743/168108925-9b2160b3-4a8a-4dc5-9623-7576e9bfaf99.png)

**Comment by majme1** [comment]
Même chose que issue 292?

https://github.com/infra-geo-ouverte/igo2/issues/292

**Comment by pelord** [comment]
dispo dans la version 1.14.2
