### ISSUE TITLE
Possibilité de changer couleur d'une couche importée

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#785]
Lors de l'importation d'une couche, la couleur est choisie au hasard, ce qui parfois peut causer problème en visualisation selon les couches affichées.  Nous voudrions pouvoir choisir à tout le moins la couleur pour pouvoir faciliter l'affichage.

**Comment by majme1** [comment]
![image](https://user-images.githubusercontent.com/57358502/180470116-b291903b-5b92-498c-a5db-d238e32b3dbd.png)

![image](https://user-images.githubusercontent.com/57358502/180470341-c1a09291-e544-4a22-b7cc-d81c9c913e80.png)


Exemples d'import de points très pâles ou difficiles à distinguer.

**Comment by majme1** [comment]
![image](https://user-images.githubusercontent.com/57358502/180470742-48c5350a-25b7-47c9-ad8d-f1548fc4365d.png)

Générer un contour seulement pour les polygones importés, actuellement il y a une couleur pleine avec transparence.

**Comment by majme1** [comment]
Même chose que issue 454?

https://github.com/infra-geo-ouverte/igo2/issues/454

**Comment by pelord** [comment]
@josee666 voir le développement du MSP pour le dessin.

**Comment by pelord** [comment]
@josee666 je suis sur le coup

**Comment by pelord** [comment]
dispo dans la prochaine version.
