### ISSUE TITLE
Ajuster le titre du menu des couches selon le contexte

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#786]
Au lieu d'avoir "Ma carte" comme titre en haut des couches, il serait intéressant d'avoir le titre du contexte:

![image](https://user-images.githubusercontent.com/56965082/168309498-baebc198-e272-48a6-b058-a85a8391f013.png)

**Comment by pelord** [comment]
@coulo3 Peut-etre rendre ca configurable.
