### ISSUE TITLE
Ajout paramètre off/on pour zoom dans options de couches

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#788]
Dans le but d'alléger la bande des options de couches, avoir la possibilité d'afficher ou non l'icône de zoom sur la couche.
Dans FO cette option serait désactivée puisque nos couches sont pratiquement toutes provinciales et cette option n'est pas utile.

![image](https://user-images.githubusercontent.com/56965082/169063764-9f898714-f9a0-4623-9d3d-6ffb60721291.png)

**Comment by majme1** [comment]
L'ajout du bouton "Aller à l'étendue de la carte" dans la 1.12 est beaucoup plus accessible et utile, on enlèvera assurément l'option de zoom sur la couche en ajoutant cet option.

Petits commentaires : inverser la position du bouton avec celui de la géolocalisation pour mettre les boutons de zoom ensemble?

![image](https://user-images.githubusercontent.com/57358502/178536774-fcd4afd4-46b9-44de-997b-65c84b735b96.png)

Pourquoi ne pas mettre le même icône que celui dans les options des couches? La maison ne me semble pas intuitive comme icône...

![image](https://user-images.githubusercontent.com/57358502/178539935-d5e0e606-1afb-4412-a28e-989786108e94.png)

**Comment by majme1** [comment]
merge avec #818 ?

**Comment by pelord** [comment]
corrigé dans 1.13.1
