### ISSUE TITLE
table attributaire et bouton filtre - filtre dans les outils VS filtre dans la table non synchronisé

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#789]
IGO version 1.11

parfois lorsque active un bouton de filtre la synchronisation entre l'interface du filtre de la table attributaire et celui de l'outil ne se fait pas automatiquement. On doit repasser le curseur sur le filtre pour que la synchronisation se produise.

NB: les données de la table et la carte sont ok et se filtrent bien le probleme semble seulement dans l'interface du bouton qui est présenté activé ou non.

![chrome_gB2bFbnley](https://user-images.githubusercontent.com/32003632/169080632-434afb00-0549-4167-adb3-689f9034710a.gif)

**Comment by majme1** [comment]
À revoir au besoin.
