### ISSUE TITLE
Détail d'un résultat de recherche

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#791]
* **Igo Version:**
1.11+

Plutot que d'avoir la flèche en bas a gauche permettant d'agrandir le résultat détaillé, il serait intéressant de simplement cliquer sur l'entête de la section pour ouvrir le résultat. 
![image](https://user-images.githubusercontent.com/7397743/169350327-d220a09c-263e-4e33-bac4-879d8b704ecc.png)

**Comment by majme1** [comment]
bonne idée, mais garder la flèche dans le visuel pareil, sinon ce n'est pas intuitif pour l'utilisateur moyen ;)
