### ISSUE TITLE
Message lorsqu'aucune couche filtrable dans ma carte

### ISSUE THREAD

**Issue by coulo3** [infra-geo-ouverte/igo2#805]
Ajouter un message "Aucune couche filtrable disponible dans la carte". 
Le filtre attributaire est disponible par défaut étant donné qu'il est possible d'ajouter une couche avec filtre via le catalogue.

![image](https://user-images.githubusercontent.com/56965082/175102927-666e0f83-2137-48fa-92f4-e9fe39c8be3c.png)

**Comment by pelord** [comment]
corrigé dans 1.13.1
