### ISSUE TITLE
Sur click du filtre dans le menu, pouvoir ouvrir les filtres par défaut

### ISSUE THREAD

**Issue by majme1** [infra-geo-ouverte/igo2#809]
Dans Forêt ouverte, lorsqu'on clic sur l'option filtre dans le menu, les filtres pour chaque couches sont masqués par défaut. L'utilisateur doit cliquer sur la flèche à gauche de la couche pour voir les boutons et/ou années pour appliquer le filtre. Ce serait préférable que les filtres soient ouverts par défaut, comme c'était le cas pour le filtre temporel. 

Filtre version 1.12
![Filtre_attributs_1 12](https://user-images.githubusercontent.com/57358502/177563942-e577596c-99ed-4dca-9d10-d43883ef93e5.PNG)

Filtre temporel version 1.11

![Filtre_temporel_1 11](https://user-images.githubusercontent.com/57358502/177563973-d12fb9ec-d75d-4e3b-9aca-7653f4f97e92.PNG)

**Please tell us about your environment:**

* **Igo Version:**

* **Node:**

**Comment by pelord** [comment]
effectif dans 1.13.1

**Comment by majme1** [comment]
Sur click de l'oeil dans l'onglet filtre, le filtre devrait s'ouvrir

![image](https://user-images.githubusercontent.com/57358502/201203729-09c080c8-9691-4803-8e89-d90057c5d697.png)
