### ISSUE TITLE
Tooltip à ajouter lorsque le bouton de géolocalisation est activé

### ISSUE THREAD

**Issue by majme1** [infra-geo-ouverte/igo2#810]
Lorsque le bouton de positionnement (geolocate) est activé, le tooltip devrait être "Masquer la géolocalisation/ Hide geolocation" vs "Afficher la géolocalisation / Show geolocation". Actuellement un seul tooltip est possible que le bouton soit activé ou non.

![Geo_off](https://user-images.githubusercontent.com/57358502/177568113-cd00cfbf-37aa-4169-9e94-5b20dafc5303.PNG)

![Geo_on](https://user-images.githubusercontent.com/57358502/177568130-fc0fe89f-b0e5-47a3-8009-d348e1c97386.PNG)

**Please tell us about your environment:**

* **Igo Version:**
* 1.12

* **Node:**

**Comment by pelord** [comment]
@mneige je t'ai assigné sur l'issue (comme tu avais fait pour [827](https://github.com/infra-geo-ouverte/igo2/issues/827))

**Comment by josee666** [comment]
@mneige @pelord  Cette demande est deja réalisée... voir PR https://github.com/infra-geo-ouverte/igo2-lib/pull/1087

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/1085

**Comment by pelord** [comment]
sera corrigé dans la version 1.13.1
