### ISSUE TITLE
Ajouter bouton "layer extent" par défaut dans les options des couches créés par les outils dessin et mesure ou les couches importées.

### ISSUE THREAD

**Issue by majme1** [infra-geo-ouverte/igo2#818]
Il me semble que le bouton de zoom sur l'étendue de la couche pourrait être particulièrement utile pour les couches créées au moyen des outils Dessiner et Mesurer, ou pour des couches importées. Est-ce que ce serait possible de l'ajouter par défaut dans les options de la couche lorsque celle-ci est générée dans ma carte?

![image](https://user-images.githubusercontent.com/57358502/180474811-6f86f38a-d683-4597-aae6-f3a8430d3629.png)

* **Igo Version:**
>1.11

**Comment by majme1** [comment]
merge avec #788 ?

**Comment by josee666** [comment]
Fait pour couche dessin et importée

**Comment by pelord** [comment]
sera intégré dans la version 1.13.1

**Comment by majme1** [comment]
Fonctionne bien pour les couches Dessins et importés, pas dispo pour les couches Mesures
