### ISSUE TITLE
Impression: ne pas imprimer la position du curseur

### ISSUE THREAD

**Issue by majme1** [infra-geo-ouverte/igo2#819]
![image](https://user-images.githubusercontent.com/57358502/180479445-835a79f6-a70f-412d-a261-908b3ab15e1f.png)

 @pelord on en avait déjà parlé je crois, mais je n'ai pas trouvé d'issue déjà là dessus, ça me semble un bug

**Comment by LAMM26** [comment]
Ok dans 16.0.0-rc.1
