### ISSUE TITLE
Pouvoir modifier le style des messages associés aux couches ou contextes

### ISSUE THREAD

**Issue by majme1** [infra-geo-ouverte/igo2#820]
Pouvoir enlever le (i) pour sauver de l'espace dans la fenêtre des messages de contextes ou de couches, pouvoir modifier le padding des listes, ajouter de la couleur au texte (bleu pour les hyperliens), etc.

![image](https://user-images.githubusercontent.com/57358502/180480168-a141365b-bb7d-4d0d-b71b-0555cf18bf80.png)

Serait intéressant de pouvoir mettre une case à cocher "j'ai compris" au lieu du x pour les messages de type warning (configurable optionnel), je pense entre autre à la mise en garde pour la couche du cadastre

![image](https://user-images.githubusercontent.com/57358502/180480478-8e97f92d-858b-4c6b-b46f-6221fc73e510.png)

@josee666

**Comment by josee666** [comment]
@majme1 @coulo3 avec la librairie tierce ngx-toaster il n'est pas possible d'utiliser un checkbox et de forcer l'utilisateur a cocher cette case. Par contre il est possible de mettre un message qui n'a pas de time out, (options.disableTimeOut:true) donc ce dernier sera toujours affiché jusqu'a ce que utilisateur click sur le message pour le faire disparaitre. Par exemple
![image](https://user-images.githubusercontent.com/32003632/183703606-dfab1c0b-4b89-47ff-93dd-70b06be65aa2.png)

NB: ajout dans la doc du param options.disableTimeOut ainsi qu'un exemple de ce genre dans la demo

**Comment by pelord** [comment]
@josee666  on ferme?

**Comment by coulo3** [comment]
Le souligné des hyperliens reste blanc
