### ISSUE TITLE
filtreOGC temporel et WFS- probleme lorsqu'on met today comme param filter.end 

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#826]
Lorsqu'on met le param filter: end: 'today' 
IGO construit la requête de filtre avec la valeur undefined dans le filtre ogc (<timePosition>). Ce qui lève une erreur au service.
`filter:` <Filter xmlns="http://www.opengis.net/ogc"><And><BBOX><PropertyName>the_geom</PropertyName><Envelope xmlns="http://www.opengis.net/gml" srsName="EPSG:3857"><lowerCorner>-7770565.789012687 6131062.151858657</lowerCorner><upperCorner>-7760676.748478292 6141639.125647618</upperCorner></Envelope></BBOX><During><ValueReference xmlns="http://www.opengis.net/fes">annee_date</ValueReference><TimePeriod `xmlns="http://www.opengis.net/gml"><begin><TimeInstant><timePosition>1930</timePosition></TimeInstant></begin><end><TimeInstant><timePosition>undefined</timePosition></TimeInstant></end></TimePeriod></During></And></Filter>`

NB: A la base (sans avoir ouvert le filtre sur la couche encore) peut être que le filtre ne devrait pas être inclus dans la requête. (A Verif lors de la correction)

Exemple de config en problème:
{
      "title": "Épidemies, chablis et verglas",
      "zIndex": 6.2,
      "visible": false,
      "workspace": {
        "enabled": true,
        "maxResolution": 10,
        "queryOptions": {
          "mapQueryOnOpenTab": false,
          "tabQuery": false
        } 
      },
      "showInLayerList": true,

      "id": "pertu_autre",

      "sourceOptions": {
          "crossOrigin": "anonymous",
          "queryable": true,
          "queryFormat": "htmlgml2",
          "queryHtmlTarget": "iframe",
          "type": "wms",
          "queryFormatAsWms": true,
          "url": "/ws/mffpecofor.fcgi",
          "optionsFromCapabilities": true,
          "params": {
              "layers": "ca_pertu_autre_close_scale",
              "version": "1.3.0"
          },
          "urlWfs": "/ws/mffpecofor.fcgi",
          "paramsWFS": {
                "featureTypes": "ca_pertu_autre_close_scale",
                "maxFeatures": 2000,
                "version": "2.0.0",
                "fieldNameGeometry": "the_geom"
          },
          "sourceFields": [
                {"name": "geoc_apm", "alias": "GEOCODE"},
                {"name": "exercice", "alias": "Année"},
                {"name": "origine", "alias": "Origine"},
                {"name": "origine_desc", "alias": "Description origine"},
                {"name": "perturb", "alias": "Perturbation"},
                {"name": "perturb_desc", "alias": "Description perturbation"},
                {"name": "superficie", "alias": "Superficie"}   
          ],
          "timeFilterable": false,
          "ogcFilters": {
              "enabled": true,
              "editable": true,
              "allowedOperatorsType": "basic",

              "filters":
              {
                "operator": "During",
                "propertyName": "annee_date",
                "begin": "1930",
                "end": "today",
                "calendarModeYear": true,
                "restrictToStep": false
              } 
          },
          "stepDate": "P1Y",
          "minDate": "1930-01-01",
          "maxDate": "2020-01-01"

      }      
    },

* **Igo Version:**
1.12

**Comment by majme1** [comment]
Solution pour contourner le problème : mettre l'année en cours comme date de fin

**Comment by majme1** [comment]
Ramener au besoin.
