### ISSUE TITLE
Géolocalisation -  Tooltip "Masquer votre position"

### ISSUE THREAD

**Issue by mneige** [infra-geo-ouverte/igo2#827]
Lorsqu'on clique sur le bouton de géolocalisation, notre position s'affiche sur la carte. Il est possible de recliquer sur le bouton de géolocalisation pour effacer notre position. Lorsque la géolocalisation est activée, le tooltip devrait afficher "Masquer votre position".

![image](https://user-images.githubusercontent.com/90412486/190186270-5df28e58-fa41-4374-85f2-b2a47a6df014.png)

* **Igo Version:**
1.12

**Comment by majme1** [comment]
Voir issue 810, j'avais noté la même chose.

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2/issues/810

cette issue sera sera fermé
