### ISSUE TITLE
Recherche - Tooltip "Effacer la recherche"

### ISSUE THREAD

**Issue by mneige** [infra-geo-ouverte/igo2#828]
Lorsqu'on a effectué une requête dans la barre de recherche, un bouton X apparaît pour effacer la recherche. 
Ajouter un tooltip "Effacer la recherche" sur le bouton X.

![image](https://user-images.githubusercontent.com/90412486/190188468-f75b518a-92cf-4308-9920-5713f9ef19b6.png)

* **Igo Version:**
1.12

**Comment by pelord** [comment]
sera appliqué dans 1.13.1
