### ISSUE TITLE
Recherche - Retirer le nombre de résultats

### ISSUE THREAD

**Issue by mneige** [infra-geo-ouverte/igo2#829]
L'outil de recherche étant basé sur Elasticsearch, le nombre de résultats est infini. Le nombre correspond donc au nombre de résultats affichés visuellement, ce qui est peu utile. Retirer le nombre et afficher seulement la catégorie de résultats.

![image](https://user-images.githubusercontent.com/90412486/190190052-bc64d73b-d164-4d3c-aca1-c1f52d2ca96a.png)

* **Igo Version:**
1.12

**Comment by pelord** [comment]
Par contre, si le nb de résultat est inférieur au seuil définit, il est intéressant de conserver le nombre.

**Comment by pelord** [comment]
Par contre, si le nb de résultat est inférieur au seuil définit, il est intéressant de conserver le nombre.

**Comment by mneige** [comment]
Ça pourrait confondre les utilisateurs de voir parfois un nombre et parfois pas. Puisque je nombre est habituellement moins que 10, ça se voit visuellement

**Comment by mneige** [comment]
À moins qu'on utilise la formulation : 
iCherche (4)
iCherche (5)
iCherche (5+)

**Comment by PhilippeLafreniere18** [comment]
Je suis d'accord avec la dernière proposition. @pelord Tu en penses quoi ?

**Comment by pelord** [comment]
@PhilippeLafreniere18 @mneige  ca me va!

**Comment by pelord** [comment]
@PhilippeLafreniere18 @mneige c'est pour 1.13.1 ?

**Comment by PhilippeLafreniere18** [comment]
Finalement, pour notre cas, on va simplement retirer le chiffre par config. À voir @pelord et @josee666 le comportement que vous souhaitez et si vous souhaitez toujours conserver le nombre de résultats
