### ISSUE TITLE
Query: pouvoir prioriser l'affichage du résultat se trouvant sur le dessus

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#831]
Présentement, quand on interroge plusieurs couches simultanément, c'est toujours la liste des résultats qui apparaît. Il serait bien de pouvoir spécifier une priorisation aux couches pour que le query s'ouvre sur ce résultat.

**Comment by majme1** [comment]
Est-ce qu'on pourrait avoir des onglets pour les différentes couches superposées au lieu d'avoir les flèches pour naviguer d'une à l'autre? Ça permettrait de voir rapidement le nombre de couches disponibles si on "bypass" la liste de résultats au premier clic.

![image](https://user-images.githubusercontent.com/57358502/190645262-3fc0a2b3-6228-436e-b8ab-6d8be6cdb136.png)

**Comment by PhilippeLafreniere18** [comment]
Oui, "presque tout" est possible ! Par contre, ce serait pas mieux d'avoir le nom de la couche au lieu d'un numéro ? Un titre raccourci qui pourrait être afficher au complet avec un tooltip

**Comment by majme1** [comment]
haha oui pour le nom de la couche, mais c'était plus simple de dessiner des numéros en exemple ;)

**Comment by gink01** [comment]
Il s'agit d'une modification qui nous intéresse, dans notre cas c'est par thématique et comme proposé nous souhaiterions que le dernier onglet consulté s'affiche par défaut à chaque interrogation. Un exemple dans notre application actuelle.


![exemple_onglet](https://user-images.githubusercontent.com/12716134/191287188-ca973554-92a9-4ec3-bcfd-8bbe46a29241.png)

**Comment by PhilippeLafreniere18** [comment]
"redirect options to a new propertie. queryOptions : { queryable: true, ..... }"

**Comment by PhilippeLafreniere18** [comment]
Pour le besoin de cet issue, la première voie à explorer serait d'afficher un champ significatif au lieu du nom de la couche.
Sinon, une configuration sur la couche permettant de sélectionner le premier résultat (si plusieurs couches ont cette config, choisir celle qui a le z index le plus élevé). @ameliebernier
