### ISSUE TITLE
Afficher un ou plusieurs plan(s), ou photo(s) individuellement en arrière-plan

### ISSUE THREAD

**Issue by gink01** [infra-geo-ouverte/igo2#833]
À partir d'une liste d'images géoréférencées établie par une sélection à l'écran ou de l'Extent en cours, permettre à l'utilisateur d'afficher une ou plusieurs images individuelles (photos, plan d'arpenteur, etc.).

**Comment by pelord** [comment]
@gink01 je vais le prendre en charge. j'ai déja un bon bout de fait.

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/1126

**Comment by pelord** [comment]
Sera dans version 16+ 
https://github.com/infra-geo-ouverte/igo2-lib/commit/f49984ff80a3d069fa625f31c9a46c64254780d0
