### ISSUE TITLE
search-pointer-summary on mobile

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#853]
The search pointer summary directive doesn't seem to be working well on mobile.

Sometimes it pops, sometimes not (mostly not).

**Comment by pelord** [comment]
@PhilippeLafreniere18 Le résumé n'est fourni que sur "pointermove". A mon souvenir, cet event n'est pas déclanché par les touch...

https://github.com/infra-geo-ouverte/igo2-lib/blob/next/packages/geo/src/lib/search/shared/search-pointer-summary.directive.ts#L222

Est-ce vraiment un bug?

**Comment by PhilippeLafreniere18** [comment]
Possible... en effet s'il n'est pas déclenché sur mobile, ce n'est tout du moins pas réglable. C'est étrange qu'il s'affiche de temps en temps par contre

**Comment by pelord** [comment]
il ne devrait pas s'afficher pourtant.. regarde cette condition ?
https://github.com/infra-geo-ouverte/igo2-lib/blob/1.13.2/packages/geo/src/lib/search/shared/search-pointer-summary.directive.ts#L261

je fermerais ...

**Comment by PhilippeLafreniere18** [comment]
Ouin peut-être le mode responsive desktop qui mêle un peu la détection de device. Je suis à l'aise à ce que l'on ferme
