### ISSUE TITLE
Impression: Imprimer les directions des itinéraires

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#859]
Pouvoir imprimer les directions lorsqu'on imprime un itinéraire ? 
Le mettre par défaut, config ?

**Comment by ameliebernier** [comment]
Proposition : ajouter un bouton "imprimer" dans le panneau de l'itinéraire? Ou on veut que ce soit à même l'outil d'impression?

**Comment by LAMM26** [comment]
Semble fonctionner dans 16.0.0-rc1
