### ISSUE TITLE
Recherche: lien google par coordonnées bug

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#861]
Le lien google ne prend plus la coordonnées au complet (seulement la latitude), ce qui brise le lien vers google maps / streetview.

![image](https://user-images.githubusercontent.com/53181414/201382097-c17acf9d-4d1c-4955-b789-1478f617afd8.png)

![image](https://user-images.githubusercontent.com/53181414/201382178-a5867d0a-7a22-432e-8fdd-5ab9f8219088.png)

**Comment by pelord** [comment]
fix attempt with https://github.com/infra-geo-ouverte/igo2-lib/compare/fixGoogleLinks?expand=1

**Comment by pelord** [comment]
réparé dans 1.13.2
