### ISSUE TITLE
Query: affichage par onglet

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#862]
Lié à https://github.com/infra-geo-ouverte/igo2/issues/831.

Serait intéressant de pouvoir afficher le query multiple avec des onglets par couche.

![image](https://user-images.githubusercontent.com/53181414/201383125-b8816e17-715c-4acb-96b3-0f834c2a2984.png)

![image](https://user-images.githubusercontent.com/53181414/201383147-39f38b8d-1ff5-44f9-8051-200283fd5f3f.png)

**Comment by pelord** [comment]
@ameliebernier a tester et a fermer apres svp.
