### ISSUE TITLE
Filtre : ouvrir sur clique de l'oeil

### ISSUE THREAD

**Issue by majme1** [infra-geo-ouverte/igo2#863]
Actuellement, le filtre est ouvert si la couche est visible. Sur click de l'oeil dans l'onglet filtre, le filtre devrait s'ouvrir également.

![image](https://user-images.githubusercontent.com/57358502/201671108-7f1371b3-84b0-45cc-bcb0-5f6f70ea225c.png)

* **Igo Version:** 1.13.1

* **Node:**

**Comment by pelord** [comment]
abandonné par manque de porteur de dossier.
