### ISSUE TITLE
X partiellement masqué

### ISSUE THREAD

**Issue by majme1** [infra-geo-ouverte/igo2#865]
X partiellement masqué lors d'une recherche de couches

![image](https://user-images.githubusercontent.com/57358502/201960521-db2023cf-fab6-4955-a038-6107fcc64dc5.png)

* **Igo Version:** 1.13.1 (le problème est absent dans la version 1.12.1)

* **Node:**

**Comment by PhilippeLafreniere18** [comment]
Lié à la maj d'Angular... je vais ajouté les autres components dans ce PR (contextes, carte, itinéraire...)

https://github.com/infra-geo-ouverte/igo2-lib/pull/1139

**Comment by pelord** [comment]
corrigé dans la prochaine version
