### ISSUE TITLE
impression pdf - titre et sous titre tronqués lors impression

### ISSUE THREAD

**Issue by josee666** [infra-geo-ouverte/igo2#874]
lors d'un impression de pdf, le titre et sous titre son tronqué car trop pres de la marge en haut.

NB: apparaisent bien sur le doc pdf, probleme lors d'une vrai impression

![image](https://user-images.githubusercontent.com/32003632/204895039-339165c3-756e-459d-af3e-330b32dcbbf7.png)

* **Igo Version:**
1.13

**Comment by pelord** [comment]
@josee666 corrigé dans quel pr?
