### ISSUE TITLE
Recherche: Enregistrer les résultats dans une nouvelle couche

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#896]

**Comment by pelord** [comment]
+1

**Comment by pelord** [comment]
Est ce que la sélection des entités à sauvegarder est fait aux niveaux des résultats de recherche OU du résultat de recherche?

C,est à dire, est ce que tous les résultats seront ajoutés à la couche ou bien, on peut sélecionner 1 seul résultat?

**Comment by PhilippeLafreniere18** [comment]
Le but sera de sélectionner un seul résultat à la fois pour ensuite choisir la couche (igo-search-layer) dans laquelle l'ajouter.

**Comment by pelord** [comment]
Est-ce que ce sera la même procédure pour les query?

**Comment by pelord** [comment]
Comment on fait pour gérer les divers champs de données dans les résultats/query et leur intégration dans les workspace?

![image](https://user-images.githubusercontent.com/7397743/216167560-43cea6aa-ebc0-407c-a672-34d38677d067.png)


vs 

![image](https://user-images.githubusercontent.com/7397743/216167602-45af88b1-b6ff-443d-b9f5-45fa22a783d6.png)

**Comment by PhilippeLafreniere18** [comment]
J'imagine que oui, le save sera mis sur le result item. Donc on pourra simplement reprendre la même logique

**Comment by PhilippeLafreniere18** [comment]
Ce ne sont que les properties ? je pense que le plus simple sera de tous les transférer. Pour nous, je ne pense que c'est pas un enjeu pour nos besoins

**Comment by pelord** [comment]
Oui. mais tu auras un workspace avec tous les champs des résultats/query que tu as sélectionné.

**Comment by PhilippeLafreniere18** [comment]
À moins qu'on le désactive par défaut à la création du layer ? Pour nous, le but n'est pas d'utiliser le workspace

**Comment by pelord** [comment]
Ok. pour les worspace! Sauf que lorsque l'ont exportera, on aura tous les champs!

**Comment by PhilippeLafreniere18** [comment]
Ouin effectivement, on pourra figurer ça dans une phase 2 !
