### ISSUE TITLE
Recherche de couche: oeil non grisé pour une couche déjà ajoutée à la carte

### ISSUE THREAD

**Issue by PhilippeLafreniere18** [infra-geo-ouverte/igo2#901]
Présentement, quand une couche est déjà présente sur la carte, mais dans sa plage de visualisation, un oeil grisé en badge l'indique dans la recherche de couche.

Il faudrait appliquer la même logique dans le cas ou une couche est dans la plage de visualisation, mais manuellement coché comme étant non visible.

**Comment by pelord** [comment]
dispo dans la version 1.14.2
