### ISSUE TITLE
Compiler les statistiques d'utilisation des couches

### ISSUE THREAD

**Issue by pelord** [infra-geo-ouverte/igo2#904]
Lors d'un ajout de couche, par le catalogue et par la recherche de couche, ce serait intéressant de compiler les "add to map" pour connaitre les couches les plus populaires/ fréquemment ajoutées.

**Comment by pelord** [comment]
Important également de monitorer quel est le catalogue source si c'Est une couche ajoutée par le catalogue

**Comment by majme1** [comment]
super ça!

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2-lib/pull/1220

Fait.
