### ISSUE TITLE
Bug possibles lors d'utilisation sur mobile

### ISSUE THREAD

**Issue by roya0045** [infra-geo-ouverte/igo2#911]
Bonjour,

Je ne sais pas si le tout est propre à IGO2 directement ou bien aux autres composantes utilisé dans l'application. Lors de test de l'application sur mobile j'ai constaté quelques éléments qui semblent problématique, mais sont tout de même minime.

1. Le bouton de géolocalisation ne semble pas fonctionner ( mes parametre d'application concernnat l'accès aux données de géolocalisation par safari sont en mode :Ask ), mais aucun pop-up n'apparait et uniquement l'icone du boutton change.
2. En effectuant des mouvement de zoom avec les doigts, l'équivalent d'un click droit est fait ce qui affiche le menu contextuel.
3. En lien avec le point précédent (je ne sais pas si le tout peut être réglé dans igo ou non), effectuer des mouvements de zoom qui touchent des éléments fixe aggrandit le zoom de la page et non la carte. Je ne sais pas à quel point le tout pourrait être problématique en temps normal, mais avec le point 2 cela est plus probable de survenir, autrement les éléments fixes qui peuvent être problématique sont surtout en périphérie (logo et autres).

**Please tell us about your environment:**

Test sur iPhone dans le furter web par défault (safari).

* **Igo Version:** 2 (https://www.foretouverte.gouv.qc.ca/ )

* **Node:**

**Comment by pelord** [comment]
Super. Merci pour les commentaires. On va essayer de les valider/corriger dans la prochaine version. Est-ce qu'on te fait signe pour valider les correctifs?

**Comment by roya0045** [comment]
> Super. Merci pour les commentaires. On va essayer de les valider/corriger dans la prochaine version. Est-ce qu'on te fait signe pour valider les correctifs?

À votre convenance, j'aimerais contribuer au projet éventuellement, mais je suis plus familier avec les applications monolithique.

**Comment by pelord** [comment]
Pour le point 2, ce serait réglé par ce changement.
https://github.com/infra-geo-ouverte/igo2-lib/pull/1205

**Comment by pelord** [comment]
pour 1, igo ne fait pas de popup de geolocalisation, c'est le fureteur qui le fait... je ne comprends pas trop comment reproduire la situation.

**Comment by pelord** [comment]
pour 3, je vais garder le pb en tête et essayer de trouver une solution.

**Comment by roya0045** [comment]
Pas de problème, je vais fermer le ticket.

**Comment by pelord** [comment]
Pour 1, si tu vas sur https://www.openstreetmap.org/ est-ce que safari te prompt/montre ta localisation?

**Comment by pelord** [comment]
ouin, faut faire 
![image](https://user-images.githubusercontent.com/7397743/228617073-35e7d7f3-529f-4f24-8f06-05fa1dc27761.png)

**Comment by roya0045** [comment]
> Pour 1, si tu vas sur https://www.openstreetmap.org/ est-ce que safari te prompt/montre ta localisation?

Même si je cliquesur l'icone et que je fais 'allow' il me donne un popup qui me dit `user denied geolocation` Le problème est possiblement de mon coté.
