### ISSUE TITLE
Résultats de recherche: Afficher l'icône d'ajout de résultats seulement au survol du résultat

### ISSUE THREAD

**Issue by LAMM26** [infra-geo-ouverte/igo2#924]
* **Igo Version:**
* 1.14.2

L'icône permettant d'ajouter un résultat de recherche dans une couche devrait être visible seulement au survol d'un résultat.

**Comment by pelord** [comment]
Attention, il faudrait être cohérent avec le catalogue et les couches cherchées.

**Comment by pelord** [comment]
dispo dans 1.15

**Comment by LAMM26** [comment]
Pour mobile, faire afficher l'icône au clic sur l'élément de recherche. Reste au survol pour desktop.
