### ISSUE TITLE
Réinitialiser la cache client de la recherche quand on change les options de recherche

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#928]
Si l'utilisateur fais une recherche -> ne trouve pas ce qu'il veut -> va changer les options de recherche, par exemple pour cibler une nouvelle catégorie qui n'était pas cochée -> refait une recherche avec le même terme pour voir si de nouveaux résultats sont disponibles, les résultats de sa première recherche sont restés en cache. Il ne voit donc pas l'effet de son changement.

**Comment by pelord** [comment]
valider le décorateur 

  @Cacheable({
    maxCacheCount: 20
  })

**Comment by ameliebernier** [comment]
Testé et c'est ok
