### ISSUE TITLE
Ajout de résultats dans une couche: Erreur lors de l'ajout d'une couche du catalogue

### ISSUE THREAD

**Issue by LAMM26** [infra-geo-ouverte/igo2#946]
Lorsque l'on crée une couche de résultats de recherche puis qu'on désire ajouter une couche du catalogue depuis la recherche, la couche n'est pas ajoutée à la carte.

**Comment by pelord** [comment]
Je suis sur le coup.

**Comment by pelord** [comment]
résolu par https://github.com/infra-geo-ouverte/igo2-lib/pull/1248

**Comment by pelord** [comment]
mergé et disponible dans la prochaine version
