### ISSUE TITLE
Print: the map legend persist after the printing

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2#952]
**Description**
When printing with legend, this legend remains hooked in the DOM.
See the hamburger menu in the Navbar, we have the legend hoverring.![image](https://github.com/infra-geo-ouverte/igo2/assets/133774929/415e27ba-e6bf-48d5-9dd4-a1bd7cd1c721)

**Résultat attendu**
This element should be removed from the DOM once printing is complete.

**Please tell us about your environment:**
Operating system: Windows
Browser: Chrome

* **Igo Version:**
1.15.2

**Comment by pelord** [comment]
Beau bug!

**Comment by LAMM26** [comment]
Ok dans 16.0.0-rc.1
