### ISSUE TITLE
Contextes : Conserver le niveau de zoom

### ISSUE THREAD

**Issue by ameliebernier** [infra-geo-ouverte/igo2#981]
Quand on recharge un contexte, le même niveau de zoom n'est pas conservé. On dirait plutôt que la carte se positionne pour afficher l'extent total du contexte? Résultat, on ne voit pas les mêmes éléments que lorsque le contexte a été sauvegardé et le niveau de zoom dépend de la taille de son écran

Proposition : conserver le centre de la carte et le niveau de zoom et les utiliser pour se replacer au bon endroit au chargement du contexte.

**Comment by LAMM26** [comment]
Ok sur version 16.0.0-rc.1
