### ISSUE TITLE
Permettre de modifier les valeurs du fichier Environment pour les applications "précompilés"

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2#994]
Présentement il y a deux moyens de configurer nos applications, via le fichier `environment.ts` et le fichier `config.json`.  Pour nos applications "précompilé", par exemple le portail du GEOMSP et Forêt-ouverte, on peut seulement paramétrer le fichier `config.json`. 

### Problématique
Le fichier config n'est pas disponible au moment de l'initialisation d'Angular vu qu'on doit faire une requête asynchrone pour l'obtenir. Certaine librairie se doit d'être initialisé au stade du APP_INITIALIZER d'Angular, par exemple Sentry, qui vient remplacer le ErrorHandler d'Angular et vu que le système d'injection dépendence est synchrone on n'a pas de moyen d'obtenir le fichier de configuration au bon moment.

### Propositon
1- Dépendament de la manière dont on précompile et distribue nos applications précompilé, si chaque application à son pipeline de compilation, on pourrait ajouter un fichier `.env` qui nous permettrait d'overrider lors de la compilation le fichier `environment.ts` et nous donnerait accès à ces valeurs lors du APP_INITIALIZER.

2- Si la première proposition n'est pas possible, il faudrait revoir la manière dont on initalise l'application IGO2 et aller chercher le fichier de configuration avant de d'amorcer le processus d'initialisation d'Angular. Par contre, on dégrade la performance de tous nos applications précompilé avec cette stratégie.
Par exemple dans le `main.ts`:
```
fetch('config.json').then((config) => {
  if (environment.production) {
    enableProdMode();
  }
  platformBrowserDynamic([{ provide: CONFIG_OPTIONS, useValue: config }])
    .bootstrapModule(AppModule)
    .catch((err) => console.log(err));
});
```

**Comment by alecarn** [comment]
@mbarbeau J'aurais besoin de savoir comment qu'on distribue ces applications précompilé (Forêt-ouverte et GEOMSP). Est-ce que chaque application compile IGO2 ou on fait seulement la distribution des fichiers compilé?

Je viens de me rapeller que pour GEOMSP, on a la branche MSPNEXT donc on pourrait overrider le fichier environment mais pas pour Forêt-ouverte.

**Comment by pelord** [comment]
Le overhead pour accèder au config.json ne doit pas etre immense non plus...? est-ce significatif?

**Comment by mbarbeau** [comment]
Une prémisse de base de IGO est qu'il peut être utilisé et configuré sans recompiler le code avec seulement les configs et les contextes. J'aurais donc une préférence sur l'option #2.

**Comment by alecarn** [comment]
J'ai aussi l'impression que la proposition #2 serait un compromis acceptable.

Dans le pipeline du Geoportail du MSP, on fait quelque chose de similaire pour configurer des élément SEO dans notre index.html. On pourrait en profiter pour repatrier ce bout de code dans IGO2 et voir si c'est fonctionnel avec la proposition #2.
