### ISSUE TITLE
Changer les logos qui pointe vers IGO1

### ISSUE THREAD

**Issue by alecarn** [infra-geo-ouverte/igo2#999]
Faire le tour des urls qui pointent encore vers igo1. Héberger le logo directement dans les fichiers statiques de l'application.

Le url a remplacer: `gouvouvert/public/images/quebec/gouv_qc_logo.png`

Le logo a héberger... a venir

**Comment by mbarbeau** [comment]
![image](https://github.com/infra-geo-ouverte/igo2/assets/2047019/66d77206-e34a-4426-bcf8-467b0ac0b06c)

**Comment by mbarbeau** [comment]
Ne semble pas très beau...

**Comment by mbarbeau** [comment]
![image](https://github.com/infra-geo-ouverte/igo2/assets/2047019/a7891381-690f-483d-b56b-433086e2c641)
https://www.piv.gouv.qc.ca/fileadmin/documents/guide/section1_general.pdf

**Comment by pelord** [comment]
J'ai pris le logo déja présent dans la l'assemblage.

**Comment by pelord** [comment]
https://github.com/infra-geo-ouverte/igo2/commit/d2bf44ecf366560142143a6f243a656e967755e3

Sera corrigé dans la version 16.
